### ISSUE TITLE
cordova-plugin-mediaで録音した音声ファイルをファイルストアにアップロードする方法は？

### ISSUE THREAD

**Issue by kasaishouhei** [NIFCloud-mbaas/UserCommunity#1006]
以下のようにMediaプラグインを使ってAndoroid,iOSAndoroid,iOS端末に音声ファイルを録音しておりました。これをncmbアップロードしたいのですがどのようなコードでやれるのか分かりません。もしよければ参考になるサンプルもしくは文献のある場所を教えてもらえるとありがたいです。

 var src = filename;
    mediaRec = new Media(src,
        // success callback
        function() {
            console.log("recordAudio():Audio Success");
        },

        // error callback
        function(err) {
            console.log("recordAudio():Audio Error: "+ err.code);
            mediaRec.release();
        }
    );

    // Record audio
    mediaRec.startRecord();
    
    // Stop recording after 30分
    setTimeout(function() {
        mediaRec.stopRecord();
    }, 1800000);
}

 var src = filename;
    mediaRec = new Media(src,
        // success callback
        function() {
            console.log("recordAudio():Audio Success");
        },

        // error callback
        function(err) {
            console.log("recordAudio():Audio Error: "+ err.code);
            mediaRec.release();
        }
    );

    // Record audio
    mediaRec.startRecord();
    
    // Stop recording after 30分
    setTimeout(function() {
        mediaRec.stopRecord();
    }, 1800000);
}

**Comment by goofmint** [comment]
こちらのやり方が参考になるかなと。 `ncmb.File.upload` でアップロードできます。

**Comment by kasaishouhei** [comment]
monacaでMediaプラグインを使って録音しているのですが
ncmb.File.upload(filename, fileData).
のfileDataには何をどう入れたら良いのでしょうか？
端末内で例えば
src = music.mp3;とすれば録音して再生も出来るのですが、この録音もしたデータをどうやってfileDataに渡したら良いですか？
