### ISSUE TITLE
Push通知の送信先端末を調べるには

### ISSUE THREAD

**Issue by ayamap** [NIFCloud-mbaas/UserCommunity#1013]
iPad（iOS）端末からNCMBQueryで配信先を選んでスマホ（iPhoneかAndroid）へPush通知を送ろうとしています。
iPadは、配信先の端末が、iPhoneかAndroidかが解っていない状況です。
この場合、配信先がどちらのOSの端末になるか調べて送信することは可能ですか。
可能な場合、その方法を教えていただけますでしょうか。

**Comment by goofmint** [comment]
配信先の端末はどう絞り込んでいるでしょうか？配信先のリストに対してiOSまたはAndroidの情報を追加するのは難しいですか？

**Comment by ayamap** [comment]
スマホ側には、NCMBInstallationのsetObjectを使ってユニークな番号を付け、通知先を特定しています。
しかしながら、そのスマホがいずれのOSかiPad側が知るすべを持っていません。

**Comment by goofmint** [comment]
2回APIをたたきますが、targetsをandroid、iosそれぞれを指定して実行する方法はどうでしょう。特定のobjectIdを指定して配信している場合、どちらかは必ず対象が0件になりますが。

**Comment by ayamap** [comment]
それぞれを指定してたたく方法、旨くいきました。
ありがとうございます。
