### ISSUE TITLE
Push通知のリクエストコンテントについて

### ISSUE THREAD

**Issue by ayamap** [NIFCloud-mbaas/UserCommunity#1014]
iPadからスマホ（iPhoneやAndroid）にPush通知を送信しようとしています。
リクエストコンテントは、OS（iOS、Android）によって設定可能な情報が異なっていますが、iOS端末へ「タイトル」を設定して送る方法はありますか。
WebのNCMB管理画面からPush通知を送る場合は、iOSの場合も「タイトル」と設定して送ることができるようになっています。

**Comment by goofmint** [comment]
エラーチェックをしている訳ではないので、

```swift
push.setTitle("-----Title-----")
```

でいけるはずです。

https://github.com/NIFCloud-mbaas/ncmb_ios/blob/master/NCMB/NCMBPush.m#L249

**Comment by ayamap** [comment]
[push setObject:@"------Title------" forKey:@"title"]; 動きました。
有り難うございます。
