### ISSUE TITLE
音声ファイルのサイズについて

### ISSUE THREAD

**Issue by kasaishouhei** [NIFCloud-mbaas/UserCommunity#1015]
monaca、JavaScriptを使い音声をアップロードするアプリのコーディングをしています。
AndoroidではCordovaのMediaプラグイン、iOSではMedia Captureプラグインを使いncmbへ、アップロードしているのですが、約三秒の音声データで
Andoroidで録音したファイルのサイズが5,257Byteなのに対して、iOSで録音した360,720Byteと約68倍になっています。

多少、音声品質が悪くてもiOSの方のファイルサイズを小さいしたいのですが、どこから手をつけるべきか、なぜここまで違うのか完全に分かっていません。

サイズを小さくするのに参考になる文献やサンプルを教えていただけたら、ありがたいです。

**Comment by goofmint** [comment]
ぱっと見た感じ、プラグインレベルでは録音品質を設定することはできないようです…。一つのアイディアですが、録音されたデータを受信した後、JavaScriptで圧縮する手もあります。重たいのでワーカースレッドで実行すべきですが。

https://qiita.com/as_kuya/items/8acaa265bc740d925f4c

**Comment by kasaishouhei** [comment]
お忙しい中、返信ありがとうございます！
コーディングしてみます！

**Comment by kasaishouhei** [comment]
mobile backendのファイル制限等があることに気が付き、かなり長い音声をアップロードしたいと考えているので、できればクライアント側でwavからmp3に圧縮しようと思っているのですがサンプル等はありますでしょうか？
