### ISSUE TITLE
Google Apps Script用SDK　データ削除　destroyメソッドについて

### ISSUE THREAD

**Issue by samefrequency** [NIFCloud-mbaas/UserCommunity#1022]
Google Apps Script用SDK　データ削除　destroyメソッドを利用しているのですが、
Request.gsの73行目(return JSON.parse(contents))で止まってしまいます。
どのようにすれば解消されるかご教授頂けませんでしょうか。

`    if (path === "DELETE" && contents == "") {` 
`       return {};` 
`     }` 
`     return JSON.parse(contents);`

呼び出しているコードは、下記になります。
`  var ncmb = NCMB.init(application_key, client_key);` 
 `  var DataTest = new ncmb.DataStore("test");` 
  ` var items = DataTest.fetchAll();` 
 ` items[1].destroy();`

**Comment by goofmint** [comment]
`path` ではなく `method` でした。バージョン30にて修正してあります。こちらでいかがでしょうか？

**Comment by samefrequency** [comment]
問題なく動作しました。ご対応ありがとうございました。
