### ISSUE TITLE
NCMBInstallationのobjectIdを取得したい

### ISSUE THREAD

**Issue by AyakoHoriuchi** [NIFCloud-mbaas/UserCommunity#1023]
以前のライブラリではNCMBInstallation#getRegistrationIdInBackground()のCallback関数内で取得できたのですが、廃止になったためどうすればいいか教えていただきたいです。

**Comment by goofmint** [comment]
`final NCMBInstallation installation = NCMBInstallation.getCurrentInstallation();`

でいけるかと思います。

https://mbaas.nifcloud.com/doc/current/push/filter_android.html

**Comment by AyakoHoriuchi** [comment]
インストール＆初回initialize直後ですと、nullになる確率が高いです。
こちら安定して取得できる方法はないのでしょうか？

**Comment by goofmint** [comment]
`getDeviceTokenInBackground` に変わっているようです。こちらお試しください。

**Comment by AyakoHoriuchi** [comment]
ありがとうございました。
