### ISSUE TITLE
参照された他のクラスのデータの自動削除

### ISSUE THREAD

**Issue by kasaishouhei** [NIFCloud-mbaas/UserCommunity#1031]
javasctiptを使い開発をしています。

(お題)のクラスと、
皆がそのお題に対して投稿する(投稿)クラス、そのお題について評価する(評価)クラスを作りたいのですが、
ある(お題)が消されたら 関連する(投稿)と(評価)も自動で消えるようにしたいのですが、ncmbではどのように実現したら良いのかわかりません。
教えていただけるとありがたいです。

**Comment by goofmint** [comment]
NCMBでは他のオブジェクトをフックにした自動削除機能はありません。解決法としては以下があります。

- スクリプトで行う
- 投稿と評価を別クラスではなく、お題クラスの中に入れてしまう

**Comment by kasaishouhei** [comment]
分かりました。ありがとうございました！
