### ISSUE TITLE
Google Apps Script用SDK ニフクラ　ドメイン変更について

### ISSUE THREAD

**Issue by samefrequency** [NIFCloud-mbaas/UserCommunity#1034]
下記のように公式インフォメーションがでておりますが、Google Apps Script用SDKのfqdn変更等の予定はございますでしょうか。
https://mbaas.nifcloud.com/info/2018/09/schedule-migration.html

**Comment by goofmint** [comment]
バージョン幾つからか忘れてしまったのですが、すでに変更されています。最新版をご利用ください！

**Comment by samefrequency** [comment]
バージョン24
ドメイン変更前かと思われます。
update()が動作します。

バージョン30でデータストアに登録したレコードに対し、update()が動作しません。
以前のバージョン（正確なバージョンは失念しましたがドメイン変更前）でデータストアに登録したレコードに対しては、update()が動作します。
バージョン25-27、29以降で試しましたが、バージョン30でデータストアに登録したレコードに対し、update()が動作しませんでした。

エラーメッセージ
TypeError: オブジェクト [object Object] で関数 json が見つかりません。（行 58、ファイル「Request」、プロジェクト「NCMB」）
※バージョン30の場合


バージョン30　58行目
  if (data) {
    if (data.acl) {
      data.acl = data.acl.json();
    }
    params.payload = JSON.stringify(data);
  }


※バージョン28のみエラー箇所が異なります。
バージョン28　151行目

  Data.fetchAll = function() {
    var me = this;
    var json = ncmb.Request({
      path: "/" + ncmb.version + "/classes/" + className,
      method: "GET",
      query: me.query
    });
    if (json.code) {
      // Error
      return json;
    }else{
      var ary = [];
      for (i = 0; i < json.results.length; i++) {
        var item = new me();
        item.set(json.results[i]);
        ary.push(item);
      }
      return ary;
    }
  }

**Comment by goofmint** [comment]
過去版のACLの扱いとの差異ですね。失礼しました。バージョン31で対応したかと思うのですがいかがでしょうか？

**Comment by samefrequency** [comment]
バージョン31で動作することを確認いたしました。
ご対応ありがとうございます。
