### ISSUE TITLE
Androidアプリを一度終了すると、次回起動時にデータストアへの登録・更新ができない。

### ISSUE THREAD

**Issue by Sagi-R** [NIFCloud-mbaas/UserCommunity#1039]
おわかりになる方、いらっしゃいましたらお願いします。

WebViewで開発していたアプリにJavaScriptSDKでランキング機能を付けたいと思い、HTMLファイルに下記の<script>を追加しました。

過去の自分のデータを更新し（初めての場合は新規作成し）、同時にランキングを表示する、といったものです。

Android実機でテストしたところ、最初はうまく動いたのですが、一度アプリを終了させた後、再度アプリを実行すると、
『ランキングは表示されるが、自分のデータは更新されない』という状況に陥りました。

エラーの場合、新規オブジェクトを作成するようにしていますが、それも実行されていません。
データストアを見ても、更新されていません。
アプリを再インストールすれば、また動きます。

```js
//過去の自分のスコアを検索して更新
var ScoreClass = ncmb.DataStore("Score");
ScoreClass.equalTo("name", プレイヤー名)
         .fetch()
         .then(function(result){
		       var resultscore = result.score;
                      //ここまではおそらく実行されている…？
		       if(resultscore < 現在のスコア){
		       result.set("score", 現在のスコア);
		       }
			return result.update();
          })
         .catch(function(err){
         //もし自分の名前がデータストアに無かった場合は新たに作る
              var newscore = new ScoreClass();
		newscore.set("name", プレイヤー名);
		newscore.set("score", 現在のスコア);
		newscore.save()
          });
          
//ランキングの取得
var Ranking = ncmb.DataStore("Score");
Ranking.exists("score")
	  .order("score", true)
         .limit(10)
         .fetchAll()
         .then(function(results){
             //ランキング取得後の処理
             output.innerHTML= "" ;
             for (var i=0; i<results.length;i++){
              var rankingresult = results[i];
		var namei = rankingresult.name;
		var scorei = rankingresult.score;
		output.innerHTML += namei + scorei + "<BR>";
             }
         })
         .catch(function(err){
            //エラー時の処理
            output.innerHTML= "　―読み込みに失敗しました―　" ;
          });
```

初心なコードで恥ずかしい限りですが、気づいた点がありましたら、ご教示いただければ嬉しいです。

**Comment by goofmint** [comment]
ランキングが表示されるということは、データストアへの接続自体はできるのだと思います。

なので気になるのは `ScoreClass.equalTo("name", プレイヤー名)` の結果が正しく返っているのかどうかです。fetchは結果の件数が0件であっても、thenにいくはずです。catchにいくのはエラーの場合です。今回でいえば `result.set("score", 現在のスコア);` の処理がエラーになっているかと思います。

二回目（スコア更新）時には問題なさそうなので、根本的な解決ではありませんが…。

**Comment by Sagi-R** [comment]
ありがとうございます。
調べてみたところ、おっしゃった通りアプリ側の問題で『プレイヤー名』の取得ができていなかっただけでした。。

おかげさまでなんとか無事、実装することができました。
今後も、どうぞよろしくお願いします。
