### ISSUE TITLE
UIWebViewの廃止について

### ISSUE THREAD

**Issue by okamuratetsu** [NIFCloud-mbaas/UserCommunity#1058]
iOSアプリを開発しています。
まもなくUIWebView（既にDeprecated）を使用しているとApple審査でRejectされるという話があります。
https://techracho.bpsinc.jp/yoshi-k/2019_08_28/79514

ニフクラ mobile backend iOS SDK 3.0.2 ではNCMBRichPushViewで使われているようですが、今後の対応予定はありますでしょうか？

**Comment by goofmint** [comment]
現在対応が進められています。近日中にリリースできる模様です。

https://github.com/NIFCloud-mbaas/ncmb_ios/pull/201

**Comment by okamuratetsu** [comment]
ご回答ありがとうございます。
ウォッチしておきます。
