### ISSUE TITLE
チュートリアルのクイズアプリについて

### ISSUE THREAD

**Issue by busra0929** [NIFCLOUD-mbaas/UserCommunity#1068]
チュートリアルの通りやってちゃんと動作しました．
本当にありがとうございます．
一つ変更したいところがありますが、どうしても解決できませんでした．

**一人のユーザが問題を作成したら、その問題が全てのユーザのアカウントに登録されています．作成された問題が、その問題を作成した会員のアカウンのみに登録されているようにしたいですが、色々試ししたが、成功できませんでした．**

よろしくお願いいたします．

**Comment by goofmint** [comment]
ACLの指定ではないでしょうか。全員に対して読み込み権限がついていませんか？

https://mbaas.nifcloud.com/doc/current/datastore/contents_monaca.html

**Comment by busra0929** [comment]
ご案内してくださったページから，下のUrlに行くことにしました。「ユーザーオブジェクトのセキュリティ」というところのサンプルコードを参照にして，解決できました.
https://mbaas.nifcloud.com/doc/current/sdkguide/javascript/user.html

誠にありがとうございました.
