### ISSUE TITLE
IOSでのPusherIDの設定について

### ISSUE THREAD

**Issue by yuki-manabi** [NIFCLOUD-mbaas/UserCommunity#1070]
下記サイトで、チャットアプリの参考にしているのですが、
https://blog.mbaas.nifcloud.com/entry/2018/02/28/103109

以下の、pusherIdがどこで手に入れるのかが分からず教えていただけないでしょうか？
const pusherId = 'YOUR_PUSHER_ID';

mobile backendでiOSプッシュ通知の設定をすると、参照できるようになるのでしょうか？(appleの料金がかかるので、事前にどうするとIDが手に入れられるか確認したく）

**Comment by goofmint** [comment]
PUSHER_IDはpusherで登録して取得します。

https://pusher.com/

**Comment by yuki-manabi** [comment]
@goofmint 
ありがとうございます。試したいと思います。

**Comment by goofmint** [comment]
```js
const crypto  = require("crypto");
const request = require('superagent');

module.exports = async (req, res) => {
  const sendPusher = async (authKey, secretKey, appId, body) => {
      const authTimestamp = Date.now() / 1000;
      const authVersion = '1.0';
      const medhod = 'POST';
      const path = `/apps/${appId}/events`;

      const message = {
          data: JSON.stringify({
              touser: body.touser,
              message: body.message
          }),
          name: "message",
          channel: body.chatid
      };

      const bodyMd5 = crypto
          .createHash('md5')
          .update(JSON.stringify(message))
          .digest('hex');
      const queryString = `auth_key=${authKey}&auth_timestamp=${authTimestamp}&auth_version=${authVersion}&body_md5=${bodyMd5}`;
      const authSigning = [
          medhod,
          path,
          queryString
      ].join("\n");
      const signature = crypto
          .createHmac("SHA256", secretKey)
          .update(authSigning)
          .digest("hex");
      return request
          .post(`https://api.pusherapp.com${path}?${queryString}&auth_signature=${signature}`)
          .set('Content-Type', 'application/json')
          .send(JSON.stringify(message))
  }

  (async () => {
    const response = await sendPusher('443a8868e3321344be81', 'fc4056e7e6cb5610a212', '148932', {
      touser: '',
      message: '',
      chatid: ''
    });
    res.send(await res.body);
  })();
}

```

**Comment by goofmint** [comment]
https://gist.github.com/goofmint/b098b3aeca41c3820d3d015ad9be9be3

**Comment by yuki-manabi** [comment]
const crypto  = require("crypto");
const request = require('superagent');

module.exports = async (req, res) => {
  const sendPusher = async (authKey, secretKey, appId, body) => {
      const authTimestamp = Date.now() / 1000;
      const authVersion = '1.0';
      const medhod = 'POST';
      const path = `/apps/${appId}/events`;

      const message = {
          data: JSON.stringify({
              touser: body.touser,
              message: body.message
          }),
          name: "message",
          channel: body.chatid
      };

      const bodyMd5 = crypto
          .createHash('md5')
          .update(JSON.stringify(message))
          .digest('hex');
      const queryString = `auth_key=${authKey}&auth_timestamp=${authTimestamp}&auth_version=${authVersion}&body_md5=${bodyMd5}`;
      const authSigning = [
          medhod,
          path,
          queryString
      ].join("\n");
      const signature = crypto
          .createHmac("SHA256", secretKey)
          .update(authSigning)
          .digest("hex");
      return request
          .post(`https://api.pusherapp.com${path}?${queryString}&auth_signature=${signature}`)
          .set('Content-Type', 'application/json')
          .send(JSON.stringify(message))
  }

  (async () => {
    const response = await sendPusher('06a5f9ec7fbd857a0dae', 'da12848d9c1f598f27ae', '905687', {
      touser: '',
      message: '',
      chatid: ''
    });
    res.send(await res.body);
  })();
}

**Comment by yuki-manabi** [comment]
@goofmint 
ありがとうございます。解決したと思いますのでクローズいたします。
