### ISSUE TITLE
iphone11で時刻表示とツールバー表示が重なる

### ISSUE THREAD

**Issue by yuki-manabi** [NIFCLOUD-mbaas/UserCommunity#1094]
iphone11で、Monacaデバッガーを使ってアプリ開発しているのですが、
画面トップの時刻表示と、アプリのツールバー部分がかぶってしまいます。

![エラー](https://user-images.githubusercontent.com/57220391/75357827-571d6f00-58f5-11ea-9de7-f7ac82aa7d49.PNG)

iphone8では、重なることがなく正常に表示されます。

iphone11とデバッガーの相性の問題なのか、時刻表示とツールバーが重ならないような処理が必要なのか分からず、ご存知の方いらっしゃいますでしょうか？

**Comment by yuki-manabi** [comment]
iphone8ではこのような表示になります。

![iphone8表示](https://user-images.githubusercontent.com/57220391/75358166-cbf0a900-58f5-11ea-9864-09ee7d68bd22.PNG)

**Comment by goofmint** [comment]
MonacaやOnsen UIの細かい使い方については公式のQ&AであるTeratailの方が早く回答が得られるかと思います。

https://teratail.com/search?q=monaca

**Comment by yuki-manabi** [comment]
ありがとうございます。解決したのでクローズいたします。
