### ISSUE TITLE
mobile backendのプッシュ通知について

### ISSUE THREAD

**Issue by kurohoan** [NIFCLOUD-mbaas/UserCommunity#1099]
https://mbaas.nifcloud.com/doc/current/push/basic_usage_javascript.html

上記の方法でアプリからプッシュ通知が登録できるかと思いますが、これはアプリがインストールされている端末分のプッシュ通知が重複して登録されてしまうのでしょうか。
一度だけ一斉配信するプッシュ通知を自動で登録したいのですが、上記方法ですと１端末ごとにプッシュ通知を登録することになり、重複して配信されてしまわないのでしょうか。

**Comment by goofmint** [comment]
重複されないようにユニーク制約があります。そのままお使いください。

**Comment by kurohoan** [comment]
デバッグビルドで２台にインストールしてみたところ、最初にインストールしたほうの端末にはやはり２回通知がきてしまうようです。

やりたいことは以下です。
１日に一回、午前0時になった時点で他サイトからAPIで情報を取得。
本日配信すべきプッシュ通知を登録。

上記を実現したいのですが、そもそもアプリ内でやることではないのか、それとも何か別の方法があるのかご教示いただけませんでしょうか。

**Comment by goofmint** [comment]
Instrationsクラスを見てみてください。同じデバイストークンが二つ登録されているのでしょうか？

mBaaSの定期実行については、Google Apps Scriptを使うのがいいかと思います。

[GoogleAppsScriptを使ってmBaaSの定期実行処理を実装する | RE:ENGINES](https://re-engines.com/2017/11/02/mbaas/)

[Google Apps Scriptでスクリプト機能の呼び出しに対応しました - ニフクラ mobile backend（mBaaS）お役立ちブログ](https://blog.mbaas.nifcloud.com/entry/11117)

この辺りを参考にしてください。

**Comment by kurohoan** [comment]
Instrationsには異なるデバイストークンが登録されております。
プッシュ通知の登録の際に全端末に向けたプッシュ通知を登録しております。

GoogleAppScriptについては確認してみます。
ありがとうございます。

**Comment by kurohoan** [comment]
google app script を使おうとしているのですが、NCMBのライブラリにおいて
ReferenceError: User is not definedのエラーがでるようです。

下記の記事のエラーだと思うのですが、こちらの記事のスクリプトIDを指定してライブラリを検索しようとしたところ、下記のエラーが表示されます。
「スクリプトで使用されるライブラリ NCMB へのアクセス権がないか、ライブラリが削除されました。」

https://blog.mbaas.nifcloud.com/entry/2020/02/27/215429

これはなぜでしょうか。

**Comment by kurohoan** [comment]
google app scriptについては別のissueをたてようと思います。
