### ISSUE TITLE
google app scriptにて ReferenceError: User is not defined

### ISSUE THREAD

**Issue by kurohoan** [NIFCLOUD-mbaas/UserCommunity#1102]
google app script を使おうとしているのですが、NCMBのライブラリにおいて
ReferenceError: User is not definedのエラーがでるようです。

下記の記事のエラーだと思うのですが、こちらの記事のスクリプトIDを指定してライブラリを検索しようとしたところ、下記のエラーが表示されます。
「スクリプトで使用されるライブラリ NCMB へのアクセス権がないか、ライブラリが削除されました。」

https://blog.mbaas.nifcloud.com/entry/2020/02/27/215429

これはなぜでしょうか。

**Comment by goofmint** [comment]
こちら、共有の設定で不備がありました。現在は大丈夫です！

ID: `1Z8Lezd0OS6qm9W0EVQxBGx1gztqD14kXPfQxycr_rc2atOfKujiWZe7I`

**Comment by kurohoan** [comment]
ありがとうございます。
var push = new ncmb.Push();
のコードの箇所で
TypeError: ncmb.Push is not a constructor
というエラーがでるのですが、これはまだプッシュ通知に対応していないということでしょうか？

またその場合、旧バージョンのgoogle app scriptを使用することはできないのでしょうか。

**Comment by goofmint** [comment]
確かにまだPushに対応していませんでした。それほど難しいものではないので、対応は可能です（来週中頃には）。
旧バージョンを使われる場合は、v8エンジンを無効にしてご利用ください。

**Comment by kurohoan** [comment]
早々にご連絡いただきありがとうございます。
ご対応いただけるまでは旧バージョンを利用したいと思います。
ありがとうございます。

**Comment by kurohoan** [comment]
旧バージョンでは
TypeError: (class)@535b942e は関数ではありません。undefined です。
というエラーがでてしまいました。
下記の ような書き出しをしているのですが、
var push = new ncmb.Push();
の箇所でエラーとなっているようです。
これはどういった原因が考えられますでしょうか。
＊App_key、Client_keyは実際とは異なります。

```
  var ncmb = NCMB.init("App_key","Client_key");
  var push = new ncmb.Push();
```

**Comment by goofmint** [comment]
元々Pushに対応してなかったようです。最新版で対応しました。以下のようなコードになります。

```js
  var push = new ncmb.Push();
  push
    .set("immediateDeliveryFlag", true)
    .set("message", "Hello, World!")
    .set("target", ["ios", "android"])
    .save();
```

**Comment by kurohoan** [comment]
ありがとうございます！

**Comment by kurohoan** [comment]
すみません、やはり以下のコードを実行するとエラーが表示されてしまいます。
何か間違っている個所はありますでしょうか？

エラー内容
TypeError: NCMB.init is not a function（行 2、ファイル「コード」）

`
function SetPushData() {
  var ncmb = NCMB.init("App_key","Client_key");

  var push = new ncmb.Push();
  push
    .set("immediateDeliveryFlag", true)
    .set("message", "Hello, World!")
    .set("target", ["ios", "android"])
    .save();
}

`

**Comment by goofmint** [comment]
ライブラリは正しく登録しているでしょうか？旧バージョンのIDは `1yWnb7GfYsBCR-MZvi6r-TOYv_y-AV4le5P7kaG5B3iZ5VNnSk9Q55pSJ` になります。IdentifierをデフォルトのNCMBのままで取り込んでもらえれば、NCMB.i と書いた時に initが入力補完候補に出るかなと。

![ScreenShot_ 2020-04-03 11 52 56](https://user-images.githubusercontent.com/5709/78319291-d3187000-75a1-11ea-820a-1ba68a997f60.png)

**Comment by kurohoan** [comment]
すみません、最新版で対応したというのは旧バージョンの話でしょうか？
v8で対応していただいたのであればそちらを利用しようとおもいv8版のncmbライブラリに入れ替えたのですが、その場合下記のコードで問題ないでしょうか？

`
function SetPushData() {
var ncmb = NCMB.init("App_key","Client_key");

var push = new ncmb.Push();
push
.set("immediateDeliveryFlag", true)
.set("message", "Hello, World!")
.set("target", ["ios", "android"])
.save();
}

`

**Comment by kurohoan** [comment]
NCMB.iと入力したときに入力候補はでました。

**Comment by goofmint** [comment]
NCMB.iで入力候補が出るということは `TypeError: NCMB.init is not a function（行 2、ファイル「コード」）` ← このエラーは出ないと思うんですよね…。

v8版の場合は次のようになります。コードは同じはずです。

```js
    const applicationKey = 'YOURS';
    const clientKey = 'YOURS';
    const ncmb = new NCMB.init(applicationKey, clientKey);
    // 検索する場合
    const query = ncmb.Push.query();
    const pushes = query.fetchAll();
    Logger.log(pushes[0]);
    // 作成する場合
    const push = new ncmb.Push();
    push
        .set("immediateDeliveryFlag", true)
        .set("message", "Hello, World!")
        .set("target", ["ios", "android"])
        .save();
```

ライブラリはバージョン12からPushとInstallationをサポートしています。

**Comment by goofmint** [comment]
すみません、試してみたところエラーが出ます！確認します！

**Comment by goofmint** [comment]
すみません、修正しました。バージョン13にてエラーが出ないことを確認しました。

**Comment by kurohoan** [comment]
ありがとうございます！
無事プッシュ通知が届くようになりました。
こちらでcron処理の実装を試みたいと思います。

**Comment by kurohoan** [comment]
すみません、配信日時の指定をすると
Exception: https://mbaas.api.nifcloud.com のリクエストに失敗しました（エラー: 400）。サーバー応答の一部:
というエラーが返ってきます。
こちらも対応していただきたいのですが可能でしょうか？

push.set("deliveryTime", new Date(datetime) )

**Comment by kurohoan** [comment]
対応していただいたのでしょうか？
本日試したら登録できるようになっておりました。
