### ISSUE TITLE
プッシュ通知に特定のパラメータを仕込む方法

### ISSUE THREAD

**Issue by kurohoan** [NIFCLOUD-mbaas/UserCommunity#1111]
プッシュ通知送信時に特定のパラメータを仕込み、開いたときにそのパラメータをもとに処理を行いたいのですが、可能でしょうか？

**Comment by kurohoan** [comment]
JSONを仕込むやり方が一般的でしょうか？

**Comment by goofmint** [comment]
そうですね。ユーザ設定値を使ってください。

![ScreenShot__2020-04-07_12_31_12](https://user-images.githubusercontent.com/5709/78627246-f0b04700-78cb-11ea-902b-f41be8f5ea14.png)

**Comment by kurohoan** [comment]
ありがとうございます。助かります。
