### ISSUE TITLE
【会員管理機能】安全な自動ログインの実装について

### ISSUE THREAD

**Issue by machati** [NIFCLOUD-mbaas/UserCommunity#1113]
localstrageのカレントユーザ情報を用いて自動ログインの実装を行いたいと思っているのですが、安全な実装なのか判断できません。
恐縮なのですが、自動ログインの安全な実装方法についてご教授頂けますでしょうか。

環境、詳細は以下となります。

◆不明な点
・ログイン後、localstrageにパス含めたユーザ情報が入りますが、
　アプリの処理で使用してしまって良いものなのか判断がつかないです。

◆環境
・Monaca
・IOS
・Javascript

◆ニフクラ：会員管理機能
・メールアドレス認証

◆想定している動作
１．アプリ起動時やresumeイベント内で、セッション時間切れを判定
２．ncmb.User.logout()と  ncmb.User.prototype.logout()　でログアウトする
３．ncmb.User.getCurrentUser() でlocalstrageからカレントユーザ情報を取得
４．localstrageのカレントユーザ情報からID（アドレス）とパスワードを抽出
５．ncmb.User.loginWithMailAddress(mail, pass)でログインさせる

◆自動ログインを行いたい理由
・作成しているアプリは家計簿的なものなのですが、その仕様上、
　１週間に２～３回はアプリを開いて更新する作業が発生します。
　ニフクラの会員管理機能ではセッションの最大有効期限が１週間の為、１週間毎に
　手作業によるログイン作業が発生してしまいます。
　その不便さを出来る限り解消したいと思っています。
　
よろしくお願いいたします。

**Comment by goofmint** [comment]
> ◆不明な点
> ・ログイン後、localstrageにパス含めたユーザ情報が入りますが、
>　アプリの処理で使用してしまって良いものなのか判断がつかないです。

パスワードはmBaaSから送信されません。なので、ログアウト後は再度パスワードを入力してもらった上、認証を行う必要があります。

`ncmb.User.logout()` を行うと、ログアウト処理とlocalStorageのデータ削除を行っています。2を行った後は、3が使えなくなるはずです。

ユーザがパスワードを入力して行う認証の手間を減らしたい場合、2つの方法があります。

- ソーシャルログインを使う（Facebookなど）
- 匿名認証を組み合わせる
- パスワードを別途保存しておく

匿名認証のIDは自動で生成されますが、このIDをlocalStorageなどに保存しておくことで、1週間経ってセッションが無効になった際に再ログインに利用できます。

```js
ncmb.User. loginAsAnonymous(id)
```

ただし、IDが漏洩すると誰でもログインできるようになるというセキュリティリスクがあるので、その点ご注意ください。

パスワードを別途保存しておく場合は、Cordovaプラグインの指紋認証プラグインなどを使うとセキュアになります。このプラグインは匿名認証のIDを保存しておく上でも役立つかと思います。

https://press.monaca.io/atsushi/2898

**Comment by machati** [comment]
goofmintさん
早いご回答大変感謝します。

お手数おかけしますが、再度ご質問させて下さい。

＞パスワードはmBaaSから送信されません。なので、ログアウト後は再度パスワードを入力してもらった上、認証を行う必要があります。
→localstrageの「NCMB/アプリキー/currentuser」にパスワード情報が入っていることを確認できているのですが、この情報はmBaasから取得しているものではないのでしょうか。

＜確認方法＞
let lst = localStorage;
let lsNcmb = lst.getItem("NCMB/myアプリキー/currentUser");
alert(lsNcmb);

または
let currentUser = ncmb.User.getCurrentUser();
alert(currentUser.get("password"));


＞ncmb.User.logout() を行うと、ログアウト処理とlocalStorageのデータ削除を行っています。2を行った後は、3が使えなくなるはずです。
→大変失礼しました。記載のミスです。仰る通りです。
　1>3>4>5と実行させた場合はログインが可能だと思うのですが、
　この方法は問題がありますでしょうか。　


＞ユーザがパスワードを入力して行う認証の手間を減らしたい場合、3つの方法があります。
→ご教授ありがとうございます。
　３つの方法についてまずは調査します。

**Comment by goofmint** [comment]
失礼しました。確かにlocalStorage内のデータを見るに、パスワードがあります。ただ、これはmBaaSから返したものではなく、ログイン時に入力されたものをそのまま保存している形になります。

> 1>3>4>5と実行させた場合はログインが可能だと思うのですが、この方法は問題がありますでしょうか。　

確かに現状の仕組み上、できそうです。個人的にはlocalStorageとはいえ、平文でパスワードが残ってしまっているのが問題に感じるので、今後のアップデート次第で対応する可能性があるのではないかと思ってしまいます。

**Comment by machati** [comment]
> 確かに現状の仕組み上、できそうです。個人的にはlocalStorageとはいえ、平文でパスワードが残ってしまっているのが問題に感じるので、今後のアップデート次第で対応する可能性があるのではないかと思ってしまいます。

ご意見ありがとうございます。
localstrageにpassがある理由がどうしても分からなかったので参考になりました。
今後のアップデートの可能性を見据えて、利用しないように処理を組みたいと思います。

質問は以上ですのでクローズしたいと思います。
ご対応頂きありがとうございました。
