### ISSUE TITLE
本番用証明書でのPush通知について

### ISSUE THREAD

**Issue by ayamasan** [NIFCLOUD-mbaas/UserCommunity#1116]
こんにちは。
Push通知の本番用の件について教えて下さい。（#389に関連）

今まで開発用の証明書で問題なく動作していましたが、証明書が期限切れになったので、
これを機に本番用の証明書を作成して入れ替えました。
ところが、Push通知を発行すると配信エラーで以下のようになり通知が届きません。
{
    "description": {
        "status": "complete"
    },
    "ios": {
        "total": 1,
        "invalidToken": 1
    }
}

iOSアプリの方は、プリファイルを作成しなおし、ビルドしなおしたものを使っています。

Appleの証明書発行の選択画面では、本番用の証明書は、Sandboxでも使えるように
思われますが、NCMBの方ではじいているのでしょうか。

また、その場合、本番用のアプリを開発環境で検証することはできないのでしょうか。
（AppStoreに実際にリリースしたあと以外、確認できないのでしょうか）

**Comment by goofmint** [comment]
恐らくですが、開発用の証明書で取られたデバイストークンに対して配信していないでしょうか。デバイストークンは開発用、本番用で異なります。

一般的にですが、開発用と本番用でアプリを分ける方が多いようです。

> Appleの証明書発行の選択画面では、本番用の証明書は、Sandboxでも使えるように
思われますが、NCMBの方ではじいているのでしょうか。

はい、URLが異なるため、本番用証明書は開発環境には利用できません。

**Comment by ayamasan** [comment]
早速のご回答、有り難うございます。
いままで開発用で作成していて、今回本番用に変更したことが原因でした。
サイトでも記載されている通り、開発用と本番用で2つのアプリを作成して、
アプリも開発用と本番用で、URL、キーを使い分けるようにして動かせました。
本番用がAppleの場合、リリース後でないと動作確認できない点がやや心配ですが
それさえ気をつければ、問題ありませんでした。
