### ISSUE TITLE
javascriptによる twitter認証で twitterデベロッパーアカウント以外だと401エラーが発生

### ISSUE THREAD

**Issue by sugiura** [NIFCLOUD-mbaas/UserCommunity#1123]
お世話になります。すみません、ご教授ください。

javascriptによる twitter認証で twitterデベロッパーアカウント以外からだと、ncmbの signUpWith メソッドで 401エラー発生します。
どんなアカウントでも twitterのID, ScreenNameは正しく取れているので mbaas側で何かが気に入らないのでしょうか？
twitterデベロッパーアカウントからだと正常に signUp&signIn出来るのが不思議です、、
以下が、javascriptコードの抜粋になります。
※ ちなみに、facebook認証ではどのアカウントからでも signUp&signInが出来ております。

```
<script src="ncmb.min.js"></script>
<script type="text/javascript">

  var ncmb = new NCMB('ncmb_app_key', 'ncmb_client_key');
  var authData = {
      oauth_consumer_key: 'oauth_consumer_key',
      consumer_secret: 'consumer_secret',
      oauth_token: 'oauth_token',
      oauth_token_secret: 'oauth_token_secret',
      id: 'twitter_id',
      screen_name: 'twitter_screen_name'
  };
  var user = new ncmb.User();
  user.signUpWith("twitter", authData) // ユーザの登録
      .then(function (user) {
          return ncmb.User.loginWith(user); // SNS連携したユーザでログイン
      })
      .then(function (user) {
          console.log(user);
      })
      .catch(function (err) {
          console.log(err);
          // ここで、Error: cannot POST https://mbaas.api.nifcloud.com:443/2013-09-01/users (401)
      });
</script>

```

**Comment by sugiura** [comment]
サポートに連絡して原因がわかりました、私のミスでした。
oauth_token、oauth_token_secret はログインしたユーザのtokenを使わないとダメでした。
クローズします。

**Comment by sai26** [comment]
失礼します。同じく401で困っています。

_oauth_token、oauth_token_secret はログインしたユーザのtokenを使わないとダメ_
というのはユーザーが認証しようとした時にAccess TokenとAccess Token Secretを毎度取得する処理が必要ということでしょうか？
何卒よろしくお願い致します。

**Comment by goofmint** [comment]
そうですね。Twitter認証で、何をもって正しく認証できたかという判断は `oauth_token` と `oauth_token_secret` があるかどうかのはずです。

**Comment by sugiura** [comment]
はい。昔の記憶ですがTwitterからログインするユーザのアクセストークンを取得し、それを ncmbへ食わす必要がありました。

**Comment by sai26** [comment]
ご返答ありがとうございます！
やはりそうですか。そこらへんもncmbでやってくれるわけじゃないんですね。
恐縮ですがサンプルコードを見せていただくことはできませんでしょうか。何卒

**Comment by sugiura** [comment]
契約上コードは出せないのですが、一般的な twitter のoauth認証をコーディングするだけです。
※ oauth_consumer_keyとかを指定してoauth認証のURLに遷移し、コールバックで結果を受け取るやつ
スクラッチで作ってもそれほ大変ではない気がしますが、処理言語にあったライブラリを使うというのも一つの方法かもしれません。
phpであれば TwitterOAuthってのを前に使った事があります。
ご参考まで：https://twitteroauth.com/

**Comment by sai26** [comment]
ありがとうございます！
不躾なお願い失礼しました。
ご親切にありがとうございます！
コールバックで受け取ったトークンとトークンシークレットをsignUpWithのパラメータのoauth_tokenとoauth_token_secretに入れて実行するということですよね？

**Comment by sugiura** [comment]
その通りです！
good luck to you.

**Comment by sai26** [comment]
ありがとうございます！！
ドキュメントないので本当に助かります。
がんばります！
