### ISSUE TITLE
データストアが利用できない

### ISSUE THREAD

**Issue by squ0713** [NIFCLOUD-mbaas/UserCommunity#1129]
monacaでアプリ作成しています
以前までデータストアが機能していたのですが、アプリを久しぶりに更新し、
cordva7からcordva9へアップデートしてから機能しなくなってしまいました
コードは変更しておらず、原因がわからずに困っています

該当のコード部分：

```js
function dataA(){
  DataClass = ncmb.DataStore("dataAndroid");
  dataClass = new DataClass();
  dataClass.set("score",area3)//area3は変数データ
    .save()
    .then(function(dataClass){
      alert("送信完了");
    })
    .catch(function(err){
      alert("送信に失敗しました。"); 
    });
}
```

※dataAを実行しても、データストアに送信されず、alert( "送信に失敗しました ")が表示されてしまいます

使用環境：
monaca
cordva 9.0.0
ncmb-push-monaca-plugin v3.0.8

試したこと：
monaca上でプラグインを削除し、再度追加
nifcloud.comでアカウント登録し直し、APIキをー再設定

**Comment by goofmint** [comment]
コードは特に問題なさそうです。エラー部分が分からないので、次のようにして実行してみてもらえますか？

```js
// 元のコード
alert("送信に失敗しました。"); 

// 変更後
alert("送信に失敗しました。" + JSON.stringify(err)); 
```

これでエラーの内容が出るので、解決につながるかなと。

**Comment by squ0713** [comment]
ありがとうございます
アドバイスのようにしたところ、以下のようなエラーを知ることができました
"status":404,"method":"post","url":https://mbass.api.niftycloud.com:443/2013-09-01/classes/DataAndroid","code":"E404005","error":"No suchapplication."

code:E404005　No suchapplication　で調べてみたところ、＃652で同様の問題に対しての解消方法が記されていました

再度、アプリケーションキーとクライアントキーをコピーしなおし確認したところ直すことができました

アドバイス、本当にありがとうございました
助かりました
