### ISSUE TITLE
<input type="date"の日本語化について

### ISSUE THREAD

**Issue by yuki-manabi** [NIFCLOUD-mbaas/UserCommunity#1141]
<input type="date"を利用して、日付入力させたいのですが、
iOSでの表示の際に、January, Februaryのように月が英語になってしまいます。
![input date](https://user-images.githubusercontent.com/57220391/85218179-a589d880-b3d2-11ea-95a3-974750ad5b9c.PNG)

スマホ側の言語設定は日本語になっているのですが、monaca側では日本語化されておらず、
何か解決法があればご教授いただければ幸いです。

**Comment by goofmint** [comment]
Monaca側の問題かと思うので、そちらで質問された方が早く回答が得られるかと思います。

**Comment by yuki-manabi** [comment]
@goofmint 
ご確認ありがとうございます。
Monaca側のサポートでの問い合わせで確認いたします。
