### ISSUE TITLE
会員情報とデータストアの情報を紐付けたい

### ISSUE THREAD

**Issue by gongqihongshu** [NIFCLOUD-mbaas/UserCommunity#1143]
javascriptでログイン機能を実装したのですが、遷移したあとの画面で入力・保存したデータを会員情報（メールアドレス）と紐付けるにはどうすればよいでしょうか？

ニフクラに載っている「基本的な使い方」のポインタやリレーションだと思うのですが、あってますでしょうか？その場合、例として記載されているfruitやfoodが何を示すのかよく分からないので、ご解説いただけますと幸いです。

よろしくお願いいたします。

**Comment by goofmint** [comment]
データを結びつける方法は幾つかあります。

## ユーザに付属情報を追加したい

例えば電話番号、住所などです。この場合はユーザオブジェクトにデータを追加して、更新してください。

```js
currentUser
  .set('tel', tel)
  .set('address', address)
  .update();
```

## データをそのユーザだけ閲覧、更新できるようにしたい

ACLとしてユーザを設定してください

https://mbaas.nifcloud.com/doc/current/datastore/contents_javascript.html

## そのユーザ所有のデータであると表現したい

データストアにあるデータとユーザ情報を紐付ける場合は、ポインターを使ってください。

https://mbaas.nifcloud.com/doc/current/datastore/basic_usage_javascript.html#%E3%83%9D%E3%82%A4%E3%83%B3%E3%82%BF

fruitやfoodはサンプルなので、特に意味はないです。単に `item.set('user', currentUser)` みたいにしてもらえればOKです（この場合の item もサンプルであって、特に意味はないです）。

- ユーザ : データ = 1 : n の場合はユーザに情報を紐付けてください。 `currentUser.set('item', item)` という形です。
- データ : ユーザ = 1 : n の場合はデータに情報を紐付けてください。 `item.set('user', currentUser)` という形です。

**Comment by gongqihongshu** [comment]
ありがとうごいます！
返事が遅くなりもうしわけございません。
無事できました！！

すみません、もう一つ質問させていただきたいのですが、
上記で登録したユーザーデータを、そのユーザーのHTML上に表示させるにはどうしたらよろしいでしょうか？
fetchAll()を使うということで正しいでしょうか？
上手く表示されなくて・・・。

**Comment by goofmint** [comment]
実際に表示はライブラリやフレームワークによって異なるので何とも…。データ自体は `currentUser.get('tel')` などで取得できます。

**Comment by gongqihongshu** [comment]
そうですよね・・・失礼いたしました

お教えいただきありがとうございました！
かなり理解が進みました！
またお願いいたします！！
