### ISSUE TITLE
swiftでのNCMBで会員クラスのデータ取得、保存について

### ISSUE THREAD

**Issue by hirai-kazumasa** [NIFCLOUD-mbaas/UserCommunity#1159]
会員管理のデータ取得を行おうと、
下記のコードを実行すると、こちらのエラーが表示され取得できません。
`NCMBApiError(code: "E403003", error: "Operation that are prohibited.")`

下記のコードでデータストアのクラスの値を取得することは出来るのですが、
会員管理クラスは出来ないのでしょうか？

保存も同じく会員クラスにデータをアプリ側から保存することは出来ないのでしょうか？

ご教示お願い致します。

        //testクラスを検索するNCMBQueryを作成
        let query : NCMBQuery<NCMBObject> = NCMBQuery.getQuery(className: "user")
     
        //データストアでの検索を行う
        query.findInBackground(callback: { result in
            switch result {
            case let .success(array):
                
                print("取得に成功しました 件数: \(array.count)")
                self.objectCount = array.count
                
                //リスト分objectデータを取り出す
                for objectVal in array{
                    
                    if let sei : String = objectVal["user_sei"]{
                        print(sei)
                    }
                }
                
            case let .failure(error):
                print("取得に失敗しました: \(error)")
            }
        })

**Comment by goofmint** [comment]
こちらでいかがでしょう？

```swift
let query : NCMBQuery<NCMBObject> = NCMBUser.query()
```

**Comment by goofmint** [comment]
すみません、型のミスがありました。

```swift
let userQuery : NCMBQuery<NCMBUser> = NCMBUser.query
```

詳しくはこちらをご覧ください。

https://github.com/NIFCLOUD-mbaas/ncmb_swift/blob/master/README.md#%E6%A8%99%E6%BA%96%E3%82%AF%E3%83%A9%E3%82%B9%E3%82%92%E6%A4%9C%E7%B4%A2%E3%81%99%E3%82%8B%E5%A0%B4%E5%90%88

**Comment by hirai-kazumasa** [comment]
gootmint様

ありがとうございます！
下記コードでユーザー一覧を取得することが出来ました。
コード実装だけでは取得できずプラスで、
会員情報クラスでひとつひとつのレコードの「パーミッション設定」
を"会員"から"全員"に変更する必要があるみたいでした。

        //testクラスを検索するNCMBQueryを作成
        let query : NCMBQuery<NCMBUser> = NCMBUser.query
       
        //データストアでの検索を行う
        query.findInBackground(callback: { result in
            switch result {
            case let .success(array):
        
                print("取得件数: \(array.count)")
                
                //リスト分objectデータを取り出す
                for objectVal in array{
                    if let sei : String = objectVal["name_sei"]{
                        print("ユーザー姓\(sei)")
                    }
                }
            case let .failure(error):
                print("取得に失敗しました: \(error)")
            }
        })`


こちらはユーザー一覧を取得する方法ですが、
ログインしているユーザー本人のレコード情報だけ取得したい場合、
やり方はあるのでしょうか？
objectIDを指定してデータを取得する方法はqueryの検索からは出来ない認識なのですが、
もしご存知でしたらご教示願いたいです。

**Comment by goofmint** [comment]
この方法は無理でしょうか？

```swift
let user = NCMBUser.currentUser;
user.fetchInBackground(callback: { result in
        switch result {
            case .success:
                // 取得に成功した場合の処理
                print("取得に成功しました")
                if let fieldB : String = object["fieldB"] {
                    print("fieldB value: \(fieldB)")
                }
            case let .failure(error):
                // 取得に失敗した場合の処理
                print("取得に失敗しました: \(error)")
        }
```

クエリを使った方法であれば、objectIdを指定することもできます。

```swift
query.where(field: "objectId", equalTo: objectId)
```

**Comment by hirai-kazumasa** [comment]
コメントありがとうございます！

上記コードをXcodeで試したところこのようなエラーが表示されてしまいます
該当行
`if let fieldB : String = object["fieldB"] {`
エラー内容
`Use of unresolved identifier 'object'`
[https://gyazo.com/a30c1849c9ed310ed3e9407718131ef7](url)

**Comment by hirai-kazumasa** [comment]
上記"該当行"部分を下記のように変更でいけました！
ありがとうございました！

`if let fieldB : String = user?["fieldB"] {`
