### ISSUE TITLE
NCMBリレーションについて

### ISSUE THREAD

**Issue by hirai-kazumasa** [NIFCLOUD-mbaas/UserCommunity#1164]
SwiftでのNCMBリレーションを使用する際、
会員クラスのitemフィールドにリレーションを設定しているものが下記コードとなります。

コード中に1回目,2回目とありますが、
まず、
1回目にpointerAのリレーションを設定して、
2回目は(1回目の方をコメントアウト)してコード実行し、pointerBのリレーションを設定しています。
こちらで正常に動作するのですが、
このような複数のクラスのオブジェクトのリレーションを設定する方法は良しとされているのでしょうか？

調べて見る限り、どれもひとつのクラスのリレーションを設定している例しかありませんでした。

また、会員クラスのダッシュボードのリレーションを設定した「item」フィールドの「リレーション」を選択すると
1回目に追加した、pointerAのオブジェクト情報にしか遷移せず、pointerBのほうは表示されません。
ですが、表示されたpointerAのレコードを削除し、再度「item」の「リレーション」を確認すると、
pointerBの情報が表示されます。
ダッシュボードで複数クラスのリレーション情報を確認する方法はないのでしょうか？

```
        // testクラスへのNCMBObjectを設定
        let user = NCMBUser.currentUser
        let pointerA = NCMBPointer(className: "TestA", objectId: "aeafafawega") ← 1回目
        //let pointerB = NCMBPointer(className: "TestB", objectId: "rajhjkhkhkhl") ← 2回目
        
        user!["item"] = NCMBAddRelationOperator(elements: [pointerA]) ← 1回目
        //user!["item"] = NCMBAddRelationOperator(elements: [pointerB]) ← 2回目
        
        // データストアへの登録を実施
        user!.saveInBackground(callback: { result in
            switch result {
            case .success:
                // 保存に成功した場合の処理
                print("保存に成功")
            case let .failure(error):
                // 保存に失敗した場合の処理
                print("保存に失敗: \(error)")
            }
        })
```

**Comment by goofmint** [comment]
> このような複数のクラスのオブジェクトのリレーションを設定する方法は良しとされているのでしょうか？

可か不可かでいえば可能ですね。ただ、書かれている通り、リレーションは一つのクラスしか対象にしていません。仕組み上、 リレーションは `User -> TestA` ではなく、 `TestA -> User` になっています（擬似的に表示はUserから辿れるようになっていますが）。

TestA用、TestB用のリレーションを分けて別なカラムにするのがお勧め（というか、それしかない）かなと…。

**Comment by hirai-kazumasa** [comment]
なるほど、そうなのですね！
リレーションは一つのクラスを対象という認識で、複数クラスのリレーションを紐付けたい場合は、
まず複数クラスのリレーションをまとめたクラスを作成し、そのクラスを会員クラスとリレーションするような
作成方法にしたいと思います！
ありがとうございました！
