### ISSUE TITLE
【android】データストア登録直後にobjectIdを取得したい

### ISSUE THREAD

**Issue by yuutarou22** [NIFCLOUD-mbaas/UserCommunity#1167]
現在制作しているandroidアプリで、データストアに登録した後、その登録した情報が一意であることを示すobjectidを取得したいと考えています。

REST APIのドキュメントにて、登録後のレスポンスコンテンツにobjectidが含まれておりましたが、こちらは使えるのでしょうか、、、

https://mbaas.nifcloud.com/doc/current/rest/datastore/objectRegistration.html#gsc.tab=0

どのように登録直後のobjectidを取得すれば良いか、ご教授頂けると幸いです。

**Comment by goofmint** [comment]
JavaかKotlinかで変わると思いますが…例えばJavaであれば。

```java
obj.saveInBackground(new DoneCallback() {
    @Override
    public void done(NCMBException e) {
        if (e != null) {
            //エラー発生時の処理
        } else {
            //成功時の処理
            String objectId = obj.getObjectId();
        }
    }
});
```

でいけないでしょうか？

**Comment by yuutarou22** [comment]
goofmint様、初めまして。
ご回答いただきありがとうございます。

試しましたところObjectIdの取得が無事できました…！

SDKの中身をよくよく確認してみると、`saveInBackground` の中で呼び出されている `NCMBObject.this.setServerDataToProperties(jsonData)` にて、
`this.setObjectId(res.getString("objectId"));` とObjectIdを設定している箇所がございますね。。。

迅速に対応していただき大変助かりました。
ありがとうございました。

**Comment by yuutarou22** [comment]
解決致しましたので、勝手ながらクローズ致します。
