### ISSUE TITLE
JavaScript SDKは、monaca以外のフレームワークを使ったアプリケーションで利用できますか

### ISSUE THREAD

**Issue by aktuehr** [NIFCLOUD-mbaas/UserCommunity#1173]
現在、IonicとCapacitorを利用したReactのハイブリッドアプリを開発しているのですが、  
push通知を機能として加えたいと思っています。  

[JavaScript SDK](https://mbaas.nifcloud.com/doc/current/introduction/div_quickstart_javascript.html#gsc.tab=0)がございますが、こちらは、Capacitor(/Cordova)で利用可能でしょうか？

利用可能な場合、push通知に関する実装についてヒントとなる箇所がございましたらご教示いただけますと幸いです。

**Comment by goofmint** [comment]
はい、Cordovaで利用できます。プッシュ通知はプラグインを使ってください。

https://github.com/NIFCLOUD-mbaas/monaca_push_plugin

実装方法はMonacaと同じです。

https://mbaas.nifcloud.com/doc/current/push/basic_usage_javascript.html#Monaca%20%E5%81%B4%E3%81%AE%E8%A8%AD%E5%AE%9A

**Comment by aktuehr** [comment]
@goofmint ご回答いただきありがとうございます。上記参考にサンプル実装をしてみたいと思います。
