### ISSUE TITLE
iOS起動時monaca_push_pluginでエラーが発生する

### ISSUE THREAD

**Issue by aktuehr** [NIFCLOUD-mbaas/UserCommunity#1174]
お世話になります。

`monaca_push_plugin` を利用した際に、iOSのアプリの起動時に以下のようにエラーになりますが、解消方法が分からず困っております。原因や解消方法などご教示いただけますと幸いです。（ `monaca_push_plugin` 側の issue に登録した方がよろしければ、その旨をお知らせいただけますと幸いです。）

# 実施前提
* Ionicフレームワーク と Capacitor を使っています。（ハイブリッド部分は React で書いています）
* Cordovaプラグインは、 Capacitorに反映しています（[参考](https://capacitorjs.jp/docs/cordova/using-cordova-plugins)）

# 実施した事
* ハイブリッド側のアプリケーションで `npm install ncmb-push-monaca-plugin`
* Capacitorに反映 `npx cap sync` ([参考](https://capacitorjs.jp/docs/cordova/using-cordova-plugins))
* XCodeの立ち上げ `npx cap open ios`
* 実機を接続して、Run

# エラー1
* importエラーが発生します
<img width="740" alt="スクリーンショット 2020-08-28 20 38 45" src="https://user-images.githubusercontent.com/30136823/91557354-4ff02000-e96f-11ea-8903-21d50306b2ff.png">

※ エラー1のパスを `NCMB/NCMB.h` から `NCMB.h` に変更するとこのエラーは出なくなりました

# エラー2
* エラー1を回避した後、`EXC_BREAKPOINT` というエラーが出ます。
<img width="727" alt="スクリーンショット 2020-08-28 20 35 58" src="https://user-images.githubusercontent.com/30136823/91557928-4fa45480-e970-11ea-9975-b523b37935fd.png">
※エラー2がでるタイミングは、スプラッシュ画面が表示されているタイミングです。

# 備考
* Android側は特にこのようなエラーもなく、ハイブリッド側は同じソースで動作し、デバイストークンの登録からプッシュの受信まで行える事を確認しています。

**Comment by cubenoy22** [comment]
横から失礼いたします。 @aktuehr さんから相談がありソースコードを確認させていただきましたが、  
エラー2は CapacitorCordova の AppDelegate.m が空っぽの(initがない)ため method swizzling に失敗して落ちるようでした。  
初期化を自動化させるための処理と見受けられますが、 AppDelegate に init がある前提のコードは危険と思われます。  
(これとは別にCapacitor側にもCAPAppDelegateというクラスが存在しますが、こちらにもイニシャライザはありません)

**Comment by goofmint** [comment]
コードの詳細な話については、該当リポジトリのIssueにてお願いします。

https://github.com/NIFCLOUD-mbaas/monaca_push_plugin

**Comment by aktuehr** [comment]
こちらですが、その後結局ネイティブ用のNCMBのSDKを組み込む事で解決できましたので、Closeさせていただきます。
