### ISSUE TITLE
フォアグラウンドでプッシュ通知受信した際に処理を実行したい【Monaca】

### ISSUE THREAD

**Issue by koro1129** [NIFCLOUD-mbaas/UserCommunity#1196]
MonacaとMonacaバックエンドを使用してアプリをリリースしているのですが、Monacaバックエンド終了に伴いニフクラmBaasへの移行作業中です。
プッシュ通知受信時の処理を以下のように実装しています。

◆Monacaバックエンドを使用する場合
```
monaca.cloud.Push.setHandler(function (data1, data2, data3) {
　// アプリがフォアグラウンドで通知を受け取った場合、ここの処理が実行される。

   // フォアグラウンドの有無を取得できる
　if (data2.foreground === true) {

    }
}
```

◆ニフクラmBaasを使用する場合
```
window.NCMB.monaca.setHandler((jsonData)=>{
    // jsonDataはカスタムペイロード。
　// アプリがフォアグラウンドで通知を受け取った場合、通知が届くだけでここの処理が実行されない。
})
```

ニフクラmBaasを使用していても、
フォアグラウンドで通知を受け取ったら即時に処理を実行する方法を教えていただきたいです。

以上、よろしくお願いいたします。

**Comment by goofmint** [comment]
window.NCMB.monaca.setHandler が実行されないとなると、プラグイン自体をカスタマイズしないといけないかも知れません…。または cordova-plugin-push-notification を同時に使って、受信した際の処理はそちらに任せるという方法もできるかと思います（すみません、未検証です。バッティングしてうまく動かなくなる可能性もあります）。

https://www.npmjs.com/package/cordova-plugin-push-notification

**Comment by koro1129** [comment]
ご返信ありがとうございます。

プラグインのカスタマイズは敷居が高そうですね...
一度提案していただいたプラグインや他のプラグインも試してみます。

ありがとうございます。

**Comment by koro1129** [comment]
下記のプラグインを併用して、フォアグラウンドで通知を受けとった際に処理を実行できるようになりました。
・[monaca_push_plugin](https://github.com/NIFCLOUD-mbaas/monaca_push_plugin/releases/tag/v3.0.9)
・[phonegap-plugin-push](https://github.com/zetekyinc/phonegap-plugin-push)
※phonegap-plugin-pushは[不具合](https://github.com/phonegap/phonegap-plugin-push/issues/2783)があったのでforkされたものを使用しています。

上記二つを組み合わせた際に、androidビルドで「Duplicate resources」エラーが出たので、下記のissueを参考にして対応しました。
https://github.com/NIFCLOUD-mbaas/UserCommunity/issues/1144

提案していただいた「cordova-plugin-push-notification」は最終更新日が古かったため使用できませんでした。
