### ISSUE TITLE
プッシュ通知をアプリから送信するのサンプルなどありませんか？

### ISSUE THREAD

**Issue by yuu8887** [NIFCLOUD-mbaas/UserCommunity#1200]
プッシュ通知（Android）基本的な使い方
https://mbaas.nifcloud.com/doc/current/push/basic_usage_android.html
こちらの、[プッシュ通知をアプリから送信する]の項目について、より具体的なサンプルなどありませんか？

androidアプリの開発なので、送信する場合、xmlによる投稿フォームが必要になると思うのですが、
そういった例を見つけることができません。

https://mbaas.nifcloud.com/push/index.html#linkArea01
にて紹介されております、[プッシュ通知の流れ]が正に作りたいものになります。こちらの作り方があれば最高です。
（これも男・女で選んでいますが、相手が男か女かはどんな方法で見極めるのでしょうか…？
　受信側のアプリで選択するようにしているのでしょうか？
　＞ID無料登録（即時）で、実際のプッシュ通知配信画面をご覧いただけます。とありますが、わからないです。）

受信側アプリは最低限できたので、送信側アプリをマスターしたいです。何卒よろしくお願い致します。

**Comment by goofmint** [comment]
Androidアプリからプッシュ通知を作成する場合、特にXMLを意識する必要はありません。サンプルにあるコードのままです。

```java
    NCMBPush push = new NCMBPush();
    push.setAction("com.sample.pushsample.RECEIVE_PUSH");
    push.setTitle("test title");
    push.setMessage("send push!");
    push.setTarget(new JSONArray("[android]"));
    push.setDialog(true);
    push.sendInBackground(new DoneCallback() {
        @Override
        public void done(NCMBException e) {
            if (e != null) {
                // エラー処理
            } else {
                // プッシュ通知登録後の操作
            }
        }
    });
```

絞り込みを行う場合は、Installationsクラスにフィールドを追加してください（たとえばgenderフィールド）。そのフィールドにユーザが属性を登録しておき、検索条件で絞り込みます。

```java
    NCMBPush push = new NCMBPush();
    NCMBQuery<NCMBInstallation> query = new NCMBQuery<>("installation");
    query.whereEqualTo("gender", "man");
    push.setSearchCondition(query);
    push.setMessage("男性だけ対象");
    push.sendInBackground();
```

**Comment by yuu8887** [comment]
回答ありがとうございます。
アプリを起動すると、管理画面のプッシュ通知にてプッシュ通知が送信されたことを確認致しました。
さらに改良して、アプリ起動後にメッセージを入力し、ボタンタップによって送信できるよう工夫したいと思います。
