### ISSUE TITLE
自作認証システムをニフクラの会員管理に移行する方法

### ISSUE THREAD

**Issue by nomori7010** [NIFCLOUD-mbaas/UserCommunity#1210]
認証システムを自作している会員制のWebサービス（ブラウザアプリ）があります。
そのWebサービスのモバイルアプリをMonacaで作成するのですが、この認証をニフクラの会員管理に移行するにはどういった手順で行えばよろしいでしょうか。
そういった事例について解説されているものがネット上であまりなく（当然かもしれませんが）、そもそもそういった事が現実的に可能なのでしょうか。
参考になりそうな書籍などでもいいのでご紹介いただけますと嬉しいです。

**Comment by goofmint** [comment]
既存の認証システムからの移行はこちらが参考になるかと思います。記事はMonacaバックエンドを対象としていますが、既存認証と置き換えてもらえる内容です。

https://blog.mbaas.nifcloud.com/entry/2020/11/04/174041

パスワードが可逆でない（通常そうだと思いますが）場合、メールアドレスがないと移行は難しくなります。ユーザIDとメールアドレスだけ移行して、各ユーザにパスワード再設定をしてもらう流れになります。

**Comment by nomori7010** [comment]
もし、パスワードが可逆の場合は、ニフクラに一括でインポートする方法はありますでしょうか。

**Comment by nomori7010** [comment]
参考ページの紹介ありがとうございました。
