### ISSUE TITLE
iOSアプリのプッシュ通知で使用するサーバー証明書につきまして

### ISSUE THREAD

**Issue by inoue555** [NIFCLOUD-mbaas/UserCommunity#1212]
先日、Apple Developerより、
Apple Push Notificationサービスのサーバー証明書の更新が必要となる発表がございました。
参考：https://developer.apple.com/jp/news/?id=7gx0a2lp

上記URLの内容を確認しましたところ、サーバーサイドで新しい証明書への切り替えが必要となる認識ですが、
本件のご対応状況につきまして、差し支えのない範囲でお教えいただければ幸いです。

**Comment by goofmint** [comment]
こちらに発表がありました。

https://mbaas.nifcloud.com/info/2021/02/post-134.html

特に作業は不要とのことです。

**Comment by inoue555** [comment]
情報のご共有ありがとうございました。
