### ISSUE TITLE
SDK経由でスクリプト機能を実行したときCORSでエラーになる

### ISSUE THREAD

**Issue by utautattaro** [NIFCLOUD-mbaas/UserCommunity#1218]
いつもお世話になっております。

JSSDK 3.0.1をクライアントサイドのJSから利用しています
スクリプト機能をncmbオブジェクト経由で呼び出した際にCORSエラーで進みません。
[こちらのブログ](https://blog.mbaas.nifcloud.com/entry/1241)でPOST,DELETEはCORSを外しているとあったのでスクリプト側をPOSTにしましたが変わらずはじかれました。
CURLで呼び出す想定ではないのでGETにしてJSONPにするのはライブラリを書き換えることになり、あまり現実的ではないなと思っています。

こちらscript.mbaas.api.nifcloud.comのエンドポイントはCORSの設定がされていないのでしょうか？サンプル通り記述し実行できなかったため困っています。ご確認お願いできますでしょうか。

**Comment by goofmint** [comment]
されているかと思います。私が試している限りは特に問題発生しませんでした。

サーバ側の話になると、内部調査が必要かと思います。テクニカルサポートへの問い合わせは[こちら](https://mbaas.nifcloud.com/support.htm)です。

**Comment by utautattaro** [comment]
ご回答ありがとうございます。ただやはりCORSエラーは出ています。
![image](https://user-images.githubusercontent.com/7885830/110280888-f4d66e80-801e-11eb-83ab-67bc1bffe548.png)


参考までに、以下のように記述しています

```
ncmb.Script
        .query({"id": self.user.objectId})
        .exec("POST", "getuserimage.js")
        .then(function(res){
            // 実行後処理
        })
        .catch(function(err){
            // エラー処理
            
        });
```

**Comment by goofmint** [comment]
もう解決しているかも知れませんが。POSTの場合、 query ではなく data メソッドを利用した方が良いはずです。
