### ISSUE TITLE
リッチプッシュでなくブラウザでURLを開きたい

### ISSUE THREAD

**Issue by yuu8887** [NIFCLOUD-mbaas/UserCommunity#1220]
プッシュ通知を開いた時にリッチプッシュでなく、ブラウザでURLを開くようにする方法はありますか？
 
NCMBPush.richPushHandler(this, getIntent());　の先にあるRichPushWebViewClientを
止める方法を模索していますが、そんなことができるのでしょうか。

最もやりたいことは、複数のプッシュ通知が来た時に、
開いたURLが上書きされることなく、ストックされる形でURLを表示させることです。
従って、WebViewよりもタブブラウザで開く方がやりたいことに合っていると考え、
その方法を探しております。

近しい過去質問
https://github.com/NIFCLOUD-mbaas/UserCommunity/issues/111

**Comment by yuu8887** [comment]
extendsで chrome custom tab を起動させることでユーザー自身の操作は必要ですが
なんとかブラウザでも表示させることができるようになりました。
ただ、追記したものなので、リッチプッシュもchrome custom tabも開く状態です。
        //リッチプッシュ通知の表示
        MyPush.richPushHandler(this, getIntent());
        getIntent().removeExtra("com.nifcloud.mbaas.RichUrl");
を残しつつ、リッチプッシュを表示させない方法はありますか？

**Comment by goofmint** [comment]
プッシュ通知画面のURLではなく、ユーザ設定値の一部にURLを渡してみるのはどうでしょう。そうすればリッチプッシュは開かないかと。
後は `onMessageReceived` でJSONデータを受け取って、そこでWebブラウザを開くようにするとか。

```java
@Override
public void onMessageReceived(com.google.firebase.messaging.RemoteMessage remoteMessage) {
    //ペイロードデータの取得
    Log.d(TAG, String.valueOf(remoteMessage.getData()));

    //デフォルトの通知
    super.onMessageReceived(remoteMessage);
}
```

[プッシュ通知 (Android) : 基本的な使い方 | ニフクラ mobile backend](https://mbaas.nifcloud.com/doc/current/push/basic_usage_android.html#JSON%E3%83%87%E3%83%BC%E3%82%BF%E3%81%AE%E5%8F%96%E5%BE%97%E3%82%92%E5%AE%9F%E8%A3%85)

**Comment by yuu8887** [comment]
ちょっと頂いたアドバイスとは違うのですが、
NCMBRichPushのextendsとせずに、NCMBRichPush同様にDialogのextendsにしたところ
chrome custom tabだけを起動させることができました。
