### ISSUE TITLE
【Unity × NCMB】ファイルストアから画像を取得し、unity側で表示させる方法がわかりません

### ISSUE THREAD

**Issue by sssscccc210** [NIFCLOUD-mbaas/UserCommunity#1224]
ラベルの付け方は、どのようになるかわからなかったため、追加なしとさせていただきます。

---
Unityを使って、ゲームやアプリを作成している者です。

### 問題点
この度、**NCMBのファイルストアを使用し、Unity上のImageに反映させたい**のですが、プログラムの記述の仕方がわかりません。
現状のプログラムは、以下の通りでございます。
`NCMBFile file = new NCMBFile("sakura.jpg");`
                `file.FetchAsync((byte[] fileData, NCMBException error) => {`
                  `      if (error != null)`
                   `     {`
                        `    // 失敗`
                        `    Debug.Log(error);`
                    `    }`
                    `    else`
                    `    {`
                        `    // 成功`
                        `    Debug.Log("画像の取得に成功！");`
                        `    ggobj.sprite = fileData[0];`
                    `    }`
                `});`

上のコードの、「ggobj.sprite = fileData[0];」の部分がエラー発生していて、うまくできません。
ファイルストアからsakura.jpgを取得するところまでは、できたのですが、表示させる方法が、ドキュメントを見ても、ネット検索しても全くわからないので、このように質問させていただいた次第です。

どうぞ、よろしくお願いいたします。

※追加の情報が必要な場合は、可能な限り、対応いたします。

**Comment by goofmint** [comment]
こんな感じでいかがでしょう？

```csharp
        NCMBFile file = new NCMBFile (fileName);
        // byte[] data = ;
        file.FetchAsync ((byte[] fileData, NCMBException error) => {
            if (error != null) {
                // 失敗
                Debug.Log(error);
            } else {
                // 成功
                Texture2D texture = new Texture2D(0, 0);
                texture.LoadImage(fileData);
                Rect rect = new Rect(0f, 0f, texture.width, texture.height);
                image_component.sprite = Sprite.Create (texture, rect, new Vector2 (0.5f, 0.5f));
            }
        });
```

**Comment by sssscccc210** [comment]
なるほど！！
一度Texture2D型に変換する必要があるということでしたか・・・

実行すると、うまく表示できました！
本当に、ありがとうございます！！
