### ISSUE TITLE
unityでファイルストアに保存したファイルのURLを取得したい

### ISSUE THREAD

**Issue by sawada-github** [NIFCLOUD-mbaas/UserCommunity#1228]
始めまして！！！
ファイルストアに保存したファイルのhttps用の「公開ファイルURL」を管理画面からでなく、プログラムで取得する方法はないでしょうか。

unityを使用しているのでこちらを参考にすると、保存方法は書かれていますが、URLについては書かれておらず、
https://mbaas.nifcloud.com/doc/current/filestore/basic_usage_unity.html#%E3%82%A2%E3%83%97%E3%83%AA%E3%81%8B%E3%82%89%E3%81%AE%E6%93%8D%E4%BD%9C

「NCMB.NCMBFile」クラスを見ても、特にURLを取得するようなメソッドはない様です。
https://mbaas.nifcloud.com/assets/sdk_doc/unity_3.2.3/Help/classNCMB_1_1NCMBFile.html

ファイルストアに「ファイルの保存」が成功した際に、URLも取得できるか、「ファイルの取得」でファイルを取得した際にURLを取得できる。
あるいは、URLを何らかの形で推測できれば良いのですが、試しにファイルストアに登録したファイルのURLを見ても規則性が分からず、この方法も難しいかな、と手詰まり状態です。

良い方法があればご教授いただければと思います。

**Comment by goofmint** [comment]
こちらを参考にどうぞ！

https://github.com/NIFCloud-mbaas/UserCommunity/issues/107

**Comment by sawada-github** [comment]
返信が遅くなってしまい申し訳ありません。
同じ内容の投稿が既にありましたね。土日に確認させていただきます。

**Comment by sawada-github** [comment]
すみません。確認が遅れました。
無事URLを取得、というより推測することができました。
