### ISSUE TITLE
プッシュ通知登録数の上限について

### ISSUE THREAD

**Issue by m-uchiyama-trw** [NIFCLOUD-mbaas/UserCommunity#1229]
こちらで質問して良いことなのかわからないのですが…

管理画面の「プッシュ通知」より登録したプッシュ通知が見れるかと思います。
こちらの登録数に上限はあるのでしょうか？

プッシュ通知の配信数はBasicプランですと月100万回とのことですが、管理画面の「プッシュ通知」に残っている過去に登録したプッシュ通知自体は月をまたいでも残っているようですので、これには該当しないのではないかと思いました。

どなたかご回答のほどよろしくお願いします。

**Comment by goofmint** [comment]
質問がよく分かりませんが、プッシュ通知画面に一覧できるプッシュ通知の上限ということでしょうか。それは特に制限はないかと思います。
無料の場合、月100万回という制限はありますので、100万回を超えたプッシュ通知の配信はエラーになるはずです。登録された = 配信できる、訳ではありません。

**Comment by m-uchiyama-trw** [comment]
@goofmint 
> プッシュ通知画面に一覧できるプッシュ通知の上限ということでしょうか。それは特に制限はないかと思います。

はい、そちらのことです。説明がわかりにくく申し訳ありません。

上限がないとのこと承知しました。
一覧の保存にも上限があって上限に達してしまうと月100万回の制限以内でも通知が送られなくなることがあるのか、と思い質問させていただきました。

回答いただきありがとうございました。
