### ISSUE TITLE
React Nativeでjavascript SDKを利用したい

### ISSUE THREAD

**Issue by d41ch15470** [NIFCLOUD-mbaas/UserCommunity#1233]
React Nativeでjavascript SDKを利用することは可能なのでしょうか。
データストアの登録・取得を試しに実装してみたところ以下のようなエラーが出てうまくいきません。
（APIリクエスト自体は成功しているようです。）

>  ERROR  [SyntaxError: JSON Parse error: Unexpected identifier "object"]
>  WARN  Possible Unhandled Promise Rejection (id: 1):

試したソースは下記のとおりですが、htmlで試したところ正常に動作しております。
```
// レコードの登録
testClass.save()
              .then(function() {
               Alert.alert('Success')
              })
              .catch(function(err) {
              })

// レコードの取得
testClass.fetchAll()
              .then(function(result) {
                Alert.alert('Success')
              })
              .catch(function(err) {
              })
```

このソースがReact Nativeだとコールバックの実行が行われず上記エラーが発生します。
（登録についてはレコードはできていました。）
そもそもReact Nativeでは完全な動作は難しいということなのでしょうか。

**Comment by goofmint** [comment]
標準のSDKは使えないことはないですが、エラーが出るかと思います（ネットワークライブラリの違いなど）。React Native用のSDKをコミュニティSDKとして開発していますので、お試しください（公式サポート対象外です）。

https://github.com/NCMBMania/ncmb-react-native

**Comment by d41ch15470** [comment]
教えていただいたSDKで試してみたところうまくいきました。
大変助かりました。ありがとうございます！
