### ISSUE TITLE
会員情報の一括アップロードについて

### ISSUE THREAD

**Issue by vi-mina-wade** [NIFCLOUD-mbaas/UserCommunity#1237]
MonacaからNCMBに乗り換え作業を行っています。
会員情報は移行せず、新しくお客様から頂いたデータを会員登録する予定です。

CurlでAPIを呼び出して会員登録したいのですが、具体的なやり方が分かりません。
シグネチャは毎回生成しないといけないと理解しました。

Monacaを利用していた際は、会員登録時にCurlコマンドを使って登録していました。
NCMBは、手動で1会員ずつ登録しなければいけないのでしょうか？
CSVアップロードみたいなことをするにはどのように実装すればよいのか教えていただけないでしょうか？

**Comment by vi-mina-wade** [comment]
早速のご返信ありがとうございます。
上記のURL、確認済みです。

情報が後出しになってしまい大変申し訳ございません。

・Linuxの外部サーバーをお客様に用意いただいております。
・開発は弊社で実装し、運用はお客様に実施していただきます。
・お客様のローカル環境にNode.jsをインストールすることはできません。

という条件がある場合、本番環境に教えていただいたURLをベースに実装したプログラムを配置して動かすという形になるのでしょうか？

**Comment by vi-mina-wade** [comment]
ncmb-cliをインストールして、とにかく動く状況を作ることが先決だと判断いたしました。

追加の質問になってしまうのですが、こちらのスレッドで大丈夫でしょうか？

教えていただいたURLで動作確認しているのですが、CSVのフォーマットがイマイチ分かりません。

----
test.csv
----
applicationName,appVersion,badge,channels,deviceToken,deviceType,sdkVersion,timeZone,userName,mailAddress,authData
,,,,,,,,test2,test@example.com,
----
このフォーマットにしたら、以下のエラーが出ました。

[Error]
Application key and client key are required

URLには以下のカラムが必要ですとあります。

Applilcation KeyなどはCSVのどのようなカラム名で設定すればよいのかご教示いただけないでしょうか？
Monacaからの移行ができず困っております。
よろしくお願いいたします。

**Comment by goofmint** [comment]
ドキュメントを確認して下さい。後、項目がデバイストークン用に見えます。

https://github.com/goofmint/ncmb-cli

**Comment by vi-mina-wade** [comment]
ご丁寧にありがとうございます。
以下で無事動作確認できました。

ncmb csv import --classname User csvファイルパス  -b -d --object -l -a アプリケーションKey -c クライアントキー

お客様には本番環境上でコマンド実行していただく形で運用考えていきたいと思います。
クローズさせていただきます。
