### ISSUE TITLE
取得した配列データのキャストができない【Unity】

### ISSUE THREAD

**Issue by enigmantohihi** [NIFCLOUD-mbaas/UserCommunity#1241]
Unityでデータベースに送った配列（int型など）を取得したいのですが、一向にできません。

取得時の型を調べてみるとArrayList型でした。
ArrayList型をint[]型に変換する方法を調べてみると
ToArrayを使うとできるとの記事を見つけたので試してみたのですが、変換できないといったエラーが起こり失敗してしまいます。

解決策を教えていただきたいです。どうかよろしくお願いします。

**Comment by goofmint** [comment]
他に良い方法がないのか試しているところではあるのですが。`int[]` ではなく `long[]` なのは確認できました。Castだけでできそうな気もするのですが、コンパイルエラーが出ます。.NETのバージョンにもよるかと思いますが…。

```cs
        NCMBObject obj = new NCMBObject("TestClass");
        obj["numbers"] = new int[3]{1, 2, 3};
        obj.SaveAsync((NCMBException e) => {      
            obj.FetchAsync((NCMBException ex) => {
                ArrayList res = obj["numbers"] as ArrayList;
                long[] numbers = new long[res.Count];
                for (var i = 0; i < res.Count; i++) {
                    numbers[i] = (long) res[i];
                }
                Debug.Log(numbers[2]);
            });
        });
```

**Comment by enigmantohihi** [comment]
この結構前の質問にも答えてもらえるとは思いませんでした！今気づきました！すいません
この問題自体は結構前に解決したのですが質問したのを忘れて放置してしまってました。
