### ISSUE TITLE
ReactNative(Expo環境)でプッシュ通知を受け取りたい【TypeScript】

### ISSUE THREAD

**Issue by umibayashi** [NIFCLOUD-mbaas/UserCommunity#1243]
お世話になります。

ReactNative(Expo環境)でプッシュ通知を受け取りたいと思っています。
react-native-ncmbを使ってプッシュ通知を受け取っているのですが
通知が行われません。

サンプルなどありましたらご教授いただきたいです。

何卒よろしくお願い申し上げます。

**Comment by goofmint** [comment]
環境を書かれていないので詳細は分かりませんが…ブログ記事が参考になるでしょうか。

https://blog.mbaas.nifcloud.com/entry/2021/02/25/182054

なお、Expoで提供されているメソッドで取得できるデバイストークンはExpo Push Notification用デバイストークンです。純粋なデバイストークンは別なメソッドが用意されているはずです。

**Comment by umibayashi** [comment]
いただいたブログ記事も以下のブログ記事も参考にさせていただいております。
https://blog.mbaas.nifcloud.com/entry/2019/08/08/111809
https://blog.mbaas.nifcloud.com/entry/2021/02/03/230546

開発環境としましては
VS Code
node.js
yarn
Expo
TypeScript
android&iOS向けアプリの作成
プッシュ通知はニフクラ mobile backgroundを使用

ただ、これを用いてプッシュ通知を受信するにいたれていません。
私の勉強不足で大変申し訳ございません。

なので、ブログの記事の「Expoアプリのプッシュ通知をNCMBで管理する」を
ためして、Expoのデバイストークンも通常のデバイストークンも取得できています。

「React Native SDKを使ってiOSへプッシュ通知を送信する」
「Expoアプリのプッシュ通知をNCMBで管理する」
の記事に書かれているファイル本体などを見せていただくことは可能でしょうか。

**Comment by goofmint** [comment]
コードは確認します。

ちなみにexpoアプリの場合、アプリリリースしていないと受信できないはずですが、リリースされていますか？デバッグはexpoアプリのバンドルIDなので、異なるデバイストークンになります。

**Comment by umibayashi** [comment]
Expo Clientを使用して実機(android/iOS)で確認しています。

Expoのアカウントも作成してそちらとFirebaseとの接続は行いました。
Expoからのプッシュ通知はandroid/iOSともにプッシュ通知の受信はできたのですが
ニフクラからのプッシュ通知をできれば受け取りたいと思っています。

ご教授いただければ幸いです。
よろしくお願いいたします。

**Comment by goofmint** [comment]
Expoアプリでは駄目ですね。アプリのバンドルIDが違います。

**Comment by umibayashi** [comment]
そうですか。

ExpoTokenの管理をニフクラで行い、プッシュ通知自体はExpoで行うようにしてみます。
ご教授いただき、ありがとうございました。
