### ISSUE TITLE
メール認証URLの期限が切れた会員情報の一括削除について

### ISSUE THREAD

**Issue by ha-suzuki** [NIFCLOUD-mbaas/UserCommunity#1252]
NCMBの会員情報を使用したアプリを運用しています。
ユーザー登録の認証URLが無効となっているユーザーを一括で削除する方法はありますでしょうか？

【ユーザー登録現在の流れ】
１．下記URLを参考に、CSVで会員情報を一括登録
https://blog.mbaas.nifcloud.com/entry/2020/05/20/141455
２．メールを受け取ったユーザーが、メール本文のURLをクリックしてユーザー登録完了する

【問題点】
アプリ設定の会員認証で設定した時間が過ぎた、もしくは何らかの理由で、ユーザー登録の認証URLが無効となった場合、
現在は、NCMBの会員管理画面から、該当のユーザーを目視で確認して手動で削除し、もう一度登録をし直してメールを送り直しています。
ですが、今後、1000人を超えるユーザーを見込んでおり、すべてを手動で対応することが困難になってきたので、
一括で出来たら、と考えています。

ユーザー認証URLが無効となっているユーザーの一括削除について、
ご教授いただけますと幸いです。

**Comment by goofmint** [comment]
仕様によると、URLの有効期限は24時間となっています。

https://mbaas.nifcloud.com/doc/current/user/authorize_email_ios.html#%E7%A2%BA%E8%AA%8D%E3%83%A1%E3%83%BC%E3%83%AB

なので、createDate が1日前で、mailAddressConfirmがfalseになっているデータはすべて削除対象になるのではないでしょうか。なお、デフォルトのACLは該当ユーザのみが読み書きできる状態なため、APIから操作はできないはずです（ユーザ登録完了時にACLを変更しないといけないので）。管理画面から前述の条件にマッチするデータを表示して、バッチで消す形になるかと思います。

あるメールアドレスが登録済みかどうか知るためには、アプリ側でユーザがログインした際に、自分のACLを変更（たとえばAdminグループのみ読めるようにするなど）しないと、APIからメールアドレスの状態が確認できないかと思います。

**Comment by ha-suzuki** [comment]
早々のご回答ありがとうございます。

＞createDate が1日前で、mailAddressConfirmがfalseになっているデータはすべて削除対象
会員管理の画面から絞り込みができることを確認しました。

＞バッチで消す
→一括で消す…会員一覧の見出しチェックボックスをチェックして全件選択、ということで理解をしました。

ありがとうございました。
