### ISSUE TITLE
会員のupdateDateの更新タイミング

### ISSUE THREAD

**Issue by Takahiro-Tsuji** [NIFCLOUD-mbaas/UserCommunity#1253]
初心者です。swiftからログインして、データストアにデータ保存できます。しかし、古い会員のupdateDateが更新されてません。他の新しい会員は、更新されてます。
タイミングを正確に知りたいです。

**Comment by goofmint** [comment]
コードが分からないのでなんとも言えませんが、データストアを更新したからといって会員のupdateDateが更新される訳でありません。

**Comment by Takahiro-Tsuji** [comment]
> コードが分からないのでなんとも言えませんが、データストアを更新したからといって会員のupdateDateが更新される訳でありません。

さっそく、ありがとうございます。コードを貼り付けます。
        NCMBUser.logInInBackground(userName: self.userNameTextField.text!, password: self.passwordTextField.text!, callback:{ result in
            // TextFieldを空に
            DispatchQueue.main.sync {
                self.cleanTextField()
            }
            
            switch result {
                case .success:
                    // ログイン成功時の処理
/*                    DispatchQueue.main.sync {
                        self.performSegue(withIdentifier: "login", sender: self)
                    }*/
                    let user:NCMBUser = NCMBUser.currentUser!
                    print("ログインに成功しました:\(String(describing: user.objectId))")
                    self.GoBackToTimeLine()
                case let .failure(error):
                    // 保存に失敗した場合の処理
                    DispatchQueue.main.sync {
                        self.errorLabel.text = "ログインに失敗しました:\(error)"
                    }
                    print("ログインに失敗しました:\(error)")
            }
        })
おっしゃる通り、ログイン、ログアウト、データストア更新単純では、更新されません。

**Comment by goofmint** [comment]
ログインしただけではupdateDateが更新されないので、上記のコードを見る限り、更新されないのが普通に見えます。むしろ、新しい会員の場合はログインするだけで、updateDateが更新されてしまっているのでしょうか？

**Comment by Takahiro-Tsuji** [comment]
> ログインしただけではupdateDateが更新されないので、上記のコードを見る限り、更新されないのが普通に見えます。むしろ、新しい会員の場合はログインするだけで、updateDateが更新されてしまっているのでしょうか？

いえ、どの会員も、上記の条件では更新が見られませんでした。どういう条件で更新されるのか、わからないです。

今、よく見ると、昨日追加した会員２名は、createDate, updateDateが同じです。
１３日に登録した会員は、updateDateが１７日になっています。パスワードが不明になって、この会員は登録し直した記憶があります。
ということは、セッションの有効期限切れの判断に、updateDateが使えないことになるような。。最初、データストアにアクセスすると、エラーが返ってきたので、このコミュニティで、updateDateから２４時間経過すると、同じエラーとなるとのスレッドを見つけて、対応したのですが。

さらに、サンプルのSwiftLoginApp workspaceをビルドして、実行して、アプリ一覧からアプリを弾区ことで終了させて再起動したときに、必ずログイン画面が出てくるので、何故なのかな？セッションがクリアされているのかな？と考えています。

**Comment by goofmint** [comment]
> セッションの有効期限切れの判断に、updateDateが使えないことになるような

セッションの有効期限チェックにはupdateDateは使えません。なお、セッションの有効期限は調整可能で、最長1週間まで設定可能です。

SwiftLoginAppはもしかすると、起動時にログイン状態のチェックを行っていないのかも知れません。 `NCMBUser.currentUser` で表示の処理判定を行っているでしょうか？

**Comment by Takahiro-Tsuji** [comment]
> > セッションの有効期限切れの判断に、updateDateが使えないことになるような
> 
> セッションの有効期限チェックにはupdateDateは使えません。なお、セッションの有効期限は調整可能で、最長1週間まで設定可能です。
ご回答ありがとうございます。となると、
`NCMBUser.currentUser`が有効なのに、データストアの検索をしたときにエラーが発生する場合、有効期限が切れているためかどうかの判定はどうすればよろしいでしょうか？ログアウトしないで、1日過ごしてアクセスすると、そのような状態に陥ったのですが。isAuthenticatedもtrueでした。
> 
> SwiftLoginAppはもしかすると、起動時にログイン状態のチェックを行っていないのかも知れません。 `NCMBUser.currentUser` で表示の処理判定を行っているでしょうか？
私のアプリではしていますが、SwiftLoginAppではチェックしていないです。

**Comment by goofmint** [comment]
セッションの有効性をチェックする必要があります。こちらのブログ記事が参考になるかと。

https://blog.mbaas.nifcloud.com/entry/2021/05/10/170848

**Comment by Takahiro-Tsuji** [comment]
> セッションの有効性をチェックする必要があります。こちらのブログ記事が参考になるかと。
> 
> https://blog.mbaas.nifcloud.com/entry/2021/05/10/170848

ブログがあるとは知りませんでした。やっと不思議が解決されたと感じました。ありがとうございます。さっそく、実装しました。
