### ISSUE TITLE
VB.netでのシグネチャ生成について

### ISSUE THREAD

**Issue by RskManTaro** [NIFCLOUD-mbaas/UserCommunity#1254]
こんにちは。お世話になります。

共通ドキュメントのシグネチャの生成方法
（https://mbaas.nifcloud.com/doc/current/rest/common/signature.html）
をもとにVB.netでシグネチャ生成を試しています。

サンプルの署名用文字列とクライアントキーを使用してシグネチャを生成しましたが、
記載されたものと異なるものが生成されました。
誤り部分を教えていただけますでしょうか。

よろしくお願いいたします。

＋＋＋＋＋
使用したサンプル（ドキュメントのものと同じ）

・署名用文字列
GET\n
mbaas.api.nifcloud.com\n
/2013-09-01/classes/TestClass\n
SignatureMethod=HmacSHA256&SignatureVersion=2&X-NCMB-Application-Key=6145f91061916580c742f806bab67649d10f45920246ff459404c46f00ff3e56&X-NCMB-Timestamp=2013-12-02T02:44:35.452Z&where=%7B%22testKey%22%3A%22testValue%22%7D

・クライアントキー
1343d198b510a0315db1c03f3aa0e32418b7a743f8e4b47cbff670601345cf75

・生成されるはずのシグネチャ
AltGkQgXurEV7u0qMd+87ud7BKuueldoCjaMgVc9Bes=

＋＋＋＋＋

サンプルコード（VB.net）

Public Sub GetMain()

    'テスト用クライアントキー
    Dim sCntKey As String = "1343d198b510a0315db1c03f3aa0e32418b7a743f8e4b47cbff670601345cf75"
    'シグネチャ生成用
    Dim sPrm01 As String
    Dim sPrm02 As String
    Dim sPrm03 As String
    Dim sPrm04 As String

    '署名用文字列作成のための値設定
    sPrm01 = "GET" & "\n"
    sPrm02 = "mbaas.api.nifcloud.com" & "\n"
    sPrm03 = "/2013-09-01/classes/TestClass" & "\n"
    sPrm04 = "SignatureMethod=HmacSHA256&SignatureVersion=2&X-NCMB-Application-Key=6145f91061916580c742f806bab67649d10f45920246ff459404c46f00ff3e56&X-NCMB-Timestamp=2013-12-02T02:44:35.452Z&where=%7B%22testKey%22%3A%22testValue%22%7D"

    '値を結合し署名文字列とする
    Dim sShomeiMoji As String = sPrm01 & sPrm02 & sPrm03 & sPrm04

    'クライアントキーと署名用文字列を変換してシグネチャ作成
    Dim eEncoder As New System.Text.UTF8Encoding
    Dim Key() As Byte = eEncoder.GetBytes(sCntKey)
    Dim Value() As Byte = eEncoder.GetBytes(sShomeiMoji)

    Dim hHMACSHA256 As New HMACSHA256(Key)
    Dim HashCode As Byte() = hHMACSHA256.ComputeHash(Value)
    Dim sSgnt As String = Convert.ToBase64String(HashCode)

    'シグネチャ出力
    Debug.WriteLine(sSgnt)

End Sub

＋＋＋＋＋

上記を実行すると、シグネチャとして
「wmiaeO/ntQVmtdLJ6WXHCNEBEZDkK8R39088GlKDC+0=」が出力されます。
想定される出力はドキュメントだと
「AltGkQgXurEV7u0qMd+87ud7BKuueldoCjaMgVc9Bes=」となり、一致しません。
改行の結合がうまくできていないのかと思い、
「\\n」や「vbcrlf」などで結合してもサンプルとは異なる値が出力されました。

ご指摘をいただければ幸いです。

よろしくお願いいたします。

**Comment by goofmint** [comment]
VB.NETでの生成方法ではないのですが、VBAでは生成したことがあります。

https://github.com/goofmint/ncmb-excel/blob/master/clsRequest.cls#L105

こちらが参考になるでしょうか？

**Comment by RskManTaro** [comment]
goofmint様

ありがとうございます。
大変参考になりました。
VB.netにしていく中で原因が判明しました。

署名用文字列を作成するためにパラメータを結合する際の改行コードを
「vbLF」とすることでドキュメント通りのシグネチャを生成することができました。

その他の処理についても細かくいただいておりましたので、
実際にアクセス処理を作成する際に参考にさせていただきます。

ありがとうございました。
