### ISSUE TITLE
kotlinでのfetchInBackground等非同期処理について

### ISSUE THREAD

**Issue by RskManTaro** [NIFCLOUD-mbaas/UserCommunity#1255]
お世話になります。

kotlinで作成をしております。
自動ログインの作成中で、カレントユーザーの取得からfetchInBackgroundでユーザー情報の取得を試しています。

ユーザーの取得ができなかった場合はログイン画面へ遷移、
ユーザーの取得ができた場合はトップ画面に遷移となるよう考えています。

サンプルを使用してfetchInBackgroundでカレントユーザーの取得をしているのですが、
非同期処理の「待ち」が作成できずに困っています。
サンプルではProgressDialogを使用しており、現在は非推奨です。
そのためコルーチン(Coroutine)やコールバック(callback)などを追加しようとしましたが、
うまく動作させることができませんでした。

なにか御助言いただけたらと思い質問させていただきました。
よろしくお願いいたします。

以下問題のソースです

```kotlin
// 初期化
NCMB.initialize(context,
            "12345・・・・・・・・・・789",
            "abcde・・・・・・・・・・xyz"
);

        val userInfo = NCMBUser.getCurrentUser()
        Log.d("[userInfo]","【1】カレントユーザ取得処理開始")
        userInfo.fetchInBackground{ userObject, e ->
            if (e != null) {
                // ユーザー情報の取得が失敗した場合の処理
                Log.d("[fetchInBackground]","【×】カレントユーザ取得失敗")
               // カレントユーザ取得失敗フラグ
                iCurrentFlg = 0
            } else {
                // ユーザー情報の取得が成功した場合の処理
                Log.d("[fetchInBackground]","【●】カレントユーザ取得成功：" + userInfo.getUserName())
               // カレントユーザ取得成功フラグ
                iCurrentFlg = 1
            }
        }

       ​Log.d("[Finish]","【F】カレントユーザ取得処理完了")

       // ▼カレントユーザ確認処理結果をもとに処理をわける▼
        if (iCurrentFlg == 0){
            // 『ログイン画面をそのまま表示する』（取得失敗）
            Log.d("[iCurrentFlg]","【×】ログイン画面をそのまま表示する")
        }else{
            // 『トップ画面へ移動する』（取得成功）
            Log.d("[iCurrentFlg]","【●】トップ画面へ移動する")
        }

```

上記を実行するとカレントユーザー取得の成功失敗ログよりも、
カレントユーザー取得処理完了が先に出力されてしまいます。

全てのログがで終わったあとに「カレントユーザー取得失敗」が出力されている状態です。

お手数おかけし申し訳ありません。

よろしくお願いします。

**Comment by RskManTaro** [comment]
そもそも処理の考え方が違うなどもありましたら頂けたらと思います。
よろしくお願いいたします。

**Comment by goofmint** [comment]
fetchInBackground は非同期処理なので、先に `iCurrentFlg` が実行されてしまいます。

fetchInBackground -> fetch に変更でいかがでしょう？おそらくエラーの場合は例外処理になるはず。

```kotlin
var userObject = userInfo.fetch()
```

KotlinといってもKotlin SDKとJava SDKどちらも使えるはずなので、間違っていたらすみません。

https://github.com/NIFCLOUD-mbaas/ncmb_kotlin/blob/master/src/main/java/com/nifcloud/mbaas/core/NCMBUser.kt#L385

**Comment by goofmint** [comment]
Kotlin（これはJava SDKを使っていたはず）でasync/awaitなら、こちらの記事が参考になるかも。

https://blog.mbaas.nifcloud.com/entry/2019/04/15/102606

**Comment by RskManTaro** [comment]
goofmint様

ご確認いただきありがとうございます。
確かに無理に非同期にする必要はなかったです。

同期処理のFetchに変更して動作確認したところ、データなしでは例外となりました。
ひとまずこの方法で進めたいと思います。
また、
非同期部分についても参考記事をいただきありがとうございます。
async/awaitとFetchで非同期的に動かすこともできるのであれば、
非同期が必要になった際はこちらを使用したいと思います。

ご丁寧にありがとうございました。
解決しましたのでクローズさせていただきます。
