### ISSUE TITLE
UnityでNCMBのデータストアの新しく作成したレコードの中から取得しようとするとエラーが起こる

### ISSUE THREAD

**Issue by enigmantohihi** [NIFCLOUD-mbaas/UserCommunity#1260]
Unityで全国ランキングのためにNCMBを使用していました。
そこに新しい要素を加えたいと思い新しいレコードを作成したのですが、データを取得しようとすると
NCMBException: NCMBObject has no data for this key. Call FetchAsync() to get the data.というエラーが発生します。
恐らく新しく作成したレコードに何も値が入っていない(underfined となっている)からだと思います。

データを取得するとき、underfinedにぶつかってもエラーが起こらないようにする方法はあるのでしょうか？ちなみな型は数字型なので0として取得するような方法があれば教えていただきたいです。

**Comment by goofmint** [comment]
Unityの場合、Long型で受け取ろうとしているのだと思いますが、キーが存在しないとエラーになります。そのため、まずキーが存在するかどうかを `ContainsKey(KEY_NAME)` で確認してください。

例えばこんな感じでしょうか。実際に試してはいないので間違っていたらすみません。

```csharp
var num = obj.ContainsKey("score") ? (long) obj["score"] : 0;
```

**Comment by enigmantohihi** [comment]
うおおできました！ありがとうございます！
キーがあるか確認できる方法調べても全く分からなかったので助かりました！

**Comment by enigmantohihi** [comment]
すみません、ソートしても並び順がおかしくなる原因って分かったりしますか？
