### ISSUE TITLE
プロキシ接続について

### ISSUE THREAD

**Issue by MonacaSommelierOsaka** [NIFCLOUD-mbaas/UserCommunity#1262]
プロキシ接続で通信をしたいのですが、
透過型プロキシに対応していますでしょうか？

また、下記プロキシで対応していないものは
ありますでしょうか？

フォワードプロキシ、キャッシュサーバー、リバースプロキシ

よろしくお願いします。

**Comment by goofmint** [comment]
SDKの話でしょうか？

**Comment by MonacaSommelierOsaka** [comment]
RestAPIですね。

**Comment by goofmint** [comment]
REST APIならProxyの設定さえ適切に行っていれば問題ないのではないでしょうか。

対応しているの意味が不明確ですが、機能として提供しているかどうかでいえばNOです（例えばNCMBのサーバから企業内リバースプロキシサーバへアクセスするなど）。

**Comment by MonacaSommelierOsaka** [comment]
なるほど
Proxy設定さえすれば理論的には大丈夫ですよね。
ありがとうございました。
