### ISSUE TITLE
会員パスワード変更ページで独自の文字列チェックをする方法について

### ISSUE THREAD

**Issue by min-tam** [NIFCLOUD-mbaas/UserCommunity#1299]
REST APIのパスワード再発行登録APIを用いた会員パスワード変更ページにて、
高セキュリティかつ独自のパスワードポリシーを設定することは可能でしょうか？

mBaaSの仕様は「null・空文字列・空白文字のみの入力は使用できません。」とのことですが、
半角文字８文字以上など一般的なパスワード制限にしたいです。
また、カスタムページのhtml上での対応はセキュリティ上、避けたいと思っています。

ご存じの方がいらっしゃいましたら、お知恵をお貸しいただきたいです。
よろしくお願いいたします。

**Comment by goofmint** [comment]
設定などでは対応できませんね…。
やったことはないのですが、パスワードを更新する際のリクエストパラメーター（セッションなども含む）がJavaScriptで取れるのであれば、その情報を使ってスクリプトで更新する手がありそうです。その場合、スクリプト側でバリデーションを行えばできるかなと。セッション情報がHTTPOnly Cookieだと駄目ですが…。

**Comment by min-tam** [comment]
なるほど、ありがとうございます。
Javascriptを利用する方法も考えたのですが、Chromeの開発者機能で見えてしまうのでこれはこれで厳しそうです…。
結構難しそうなので運用回避する方針で考えてみようと思います。

ご回答ありがとうございました！
