### ISSUE TITLE
プッシュ通知が受信できません

### ISSUE THREAD

**Issue by S-Kaneko-5517** [NIFCLOUD-mbaas/UserCommunity#1301]
Flutterを使用してアプリを作成しています。
アプリの中でプッシュ通知を実装しようとして、FCMの受信方法で記述しました。
ですが、コンソールに「バックグラウンドでメッセージを受け取りました」と表示されるのですが
端末に通知は届いていません。

```dart
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  print("バックグラウンドでメッセージを受け取りました");
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();

  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  runApp(
    MultiProvider(
      providers: globalProviders,
      child: const MyApp(),
    ),
  );
}
```

Android Manifestやbuild.gradleの設定は、mobile backendのドキュメント　プッシュ通知（Kotlin）で設定をしました。
Flutterでは、どのようにプッシュ通知を受信するのでしょうか？
設定方法の違いや受信方法が違うなどあればご教授いただきたいです。

**Comment by S-Kaneko-5517** [comment]
追記です。
Didn't find class "com.nifcloud.mbaas.core.NCMBFirebaseMessagingService" というメッセージが表示されていました。

**Comment by goofmint** [comment]
具体的な設定という訳ではないのですが、

https://mbaas.nifcloud.com/doc/current/push/basic_usage_android.html#Android%20Manifest%E3%81%AE%E7%B7%A8%E9%9B%86

にて `com.nifcloud.mbaas.core.NCMBFirebaseMessagingService` が設定されているためではないでしょうか？そして、そのクラスが存在しないというエラーが出ているのだと思います。

https://zuma-lab.com/posts/flutter-fcm-push-notify-settings

を見る限りでは `android:name=".Application"` が良いように見えます（別途 `Application.kt` が必要なようです）。

**Comment by S-Kaneko-5517** [comment]
ご回答ありがとうございます。

java、Kotkinでは設定をしていましたが、Flutterではcom.nifcloud.mbaas.core.NCMBFirebaseMessagingServiceの設定は不要なのでしょうか？

また、ご教授いただいた上記のサイトを参照させていただき、Application.ktの作成やAndroidManifest.xmlの修正を行いましたが、Unresolved reference:  registerWithというエラーが発生し、うまくいきませんでした。

Application.ktは、Flutter Version1.12以降は不要（開発はFlutter Version2.10.4で行っています）だとの記述もありましたので、こちらは他の設定方法がないか調べたいと思っています。

サイトを教えていただきありがとうございます。

**Comment by S-Kaneko-5517** [comment]
ドキュメントの設定を見直したところNCMB.jarの設定がされていなかったため
再度、設定を最初からやり直して管理画面からプッシュ通知を送信したところ、通知の受信と同時にアプリが落ちてしまいました。

以下がログです。

D/FLTFireMsgReceiver(20742): broadcast received for message
I/System.out(20742): NCMB send start : Bundle[{title=テスト, message=テスト, com.nifcloud.mbaas.PushId=YqQUz1udnDqN2tG4}]
I/System.out(20742): channel = null
I/QarthLog(20742): [PatchStore] createDisableExceptionQarthFile
I/QarthLog(20742): [PatchStore] create disable file for com.example.package uid is 10220
E/AndroidRuntime(20742): FATAL EXCEPTION: Firebase-Messaging-Intent-Handle
E/AndroidRuntime(20742): Process: com.example.package, PID: 20742
E/AndroidRuntime(20742): java.lang.Error: com.nifcloud.mbaas.core.NCMBException: com.example.packagenull
E/AndroidRuntime(20742): 	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1193)
E/AndroidRuntime(20742): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
E/AndroidRuntime(20742): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(20742): 	at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.0.0:2)
E/AndroidRuntime(20742): 	at java.lang.Thread.run(Thread.java:929)
E/AndroidRuntime(20742): Caused by: com.nifcloud.mbaas.core.NCMBException: com.example.packagenull
E/AndroidRuntime(20742): 	at com.nifcloud.mbaas.core.NCMBFirebaseMessagingService.notificationSettings(NCMBFirebaseMessagingService.kt:226)
E/AndroidRuntime(20742): 	at com.nifcloud.mbaas.core.NCMBFirebaseMessagingService.sendNotification(NCMBFirebaseMessagingService.kt:129)
E/AndroidRuntime(20742): 	at com.nifcloud.mbaas.core.NCMBFirebaseMessagingService.onMessageReceived(NCMBFirebaseMessagingService.kt:91)
E/AndroidRuntime(20742): 	at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(FirebaseMessagingService.java:235)
E/AndroidRuntime(20742): 	at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(FirebaseMessagingService.java:185)
E/AndroidRuntime(20742): 	at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(FirebaseMessagingService.java:172)
E/AndroidRuntime(20742): 	at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(FirebaseMessagingService.java:161)
E/AndroidRuntime(20742): 	at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(EnhancedIntentService.java:78)
E/AndroidRuntime(20742): 	at com.google.firebase.messaging.-$$Lambda$EnhancedIntentService$NSk2h75eWhBOI4TsAFgvvtv1g9o.run(Unknown Source:6)
E/AndroidRuntime(20742): 	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
E/AndroidRuntime(20742): 	... 4 more
E/AndroidRuntime(20742): Caused by: java.lang.ClassNotFoundException: com.example.packagenull
E/AndroidRuntime(20742): 	at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(20742): 	at java.lang.Class.forName(Class.java:454)
E/AndroidRuntime(20742): 	at java.lang.Class.forName(Class.java:379)
E/AndroidRuntime(20742): 	at com.nifcloud.mbaas.core.NCMBFirebaseMessagingService.notificationSettings(NCMBFirebaseMessagingService.kt:222)
E/AndroidRuntime(20742): 	... 13 more
E/AndroidRuntime(20742): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.packagenull" on path: DexPathList[[zip file "/data/app/com.example.package-ZTJp0Uf78FiRWLV4gY5_Nw==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.package-ZTJp0Uf78FiRWLV4gY5_Nw==/lib/arm64, /data/app/com.example.package-ZTJp0Uf78FiRWLV4gY5_Nw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64, /hw_product/lib64, /system/product/lib64]]
E/AndroidRuntime(20742): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
E/AndroidRuntime(20742): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(20742): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(20742): 	... 17 more
I/Process (20742): Sending signal. PID: 20742 SIG: 9
Lost connection to device.
Exited (sigterm)

ファイルの設定内容は以下となっています。
### **android/build.gradle**
buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.5'
    }
}

### **app/build.gradle**
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.code.gson:gson:2.9.0'    
    api files('libs/NCMB.jar')
    implementation platform('com.google.firebase:firebase-bom:30.1.0')
    implementation 'com.google.firebase:firebase-messaging:23.0.0'
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.android.gms:play-services-base:18.0.0'
}

Application.ktは、Unresolved reference: registerWithのエラーが解決できないため作成しておりません。
Flutter Version1.12以降は不要ともありましたのでとりあえず作成せずに実行しています。

対処方法など、ご教授お願いいたします。

**Comment by goofmint** [comment]
デモコードを書いてみました。

https://github.com/NCMBMania/Flutter_Push_demo

利用しているのはpushとflutter_local_notificationsです。本来はpushだけで事足りるのですが、titleが入っていないためにローカル通知経由になっています（Androidのみ）。

Flutterプロジェクトとの初期化時の違いは↓のコミットで確認できます。

https://github.com/NCMBMania/Flutter_Push_demo/commit/949679228caa36346968ae720864a395ca78d84e

**Comment by goofmint** [comment]
ブログ記事も書いてみました。

[NCMBのFlutter SDKを使ってプッシュ通知を送信する（Android編） - Qiita](https://qiita.com/goofmint/items/bff9deb889c76d02617b)

lib/NCMB.jarは不要です。

**Comment by S-Kaneko-5517** [comment]
回答いただいたばかりか、デモコードまで書いていただいてありがとうございます。

デモコード、ブログ記事を参照させていただき無事プッシュ通知を受信することができました。

正直、ネットでも参考にできるサイトがないので、プッシュ通知機能をあきらめかけていました。

大変助かりました。ありがとうございました。
