### ISSUE TITLE
Flutter 日付の検索が失敗します。

### ISSUE THREAD

**Issue by S-Kaneko-5517** [NIFCLOUD-mbaas/UserCommunity#1303]
今日の日付で、会員データを作成した日(createDate)を絞り込み検索したいと思っています。

ですが、【コード】のquery.fetchAll()で失敗してしまいます。
try catchにも引っかからず、処理が終了してしまいます。

検索方法が違うなど、ご教授いただけますでしょうか。

【コード】
 var dt = DateTime.now();

 var query = NCMBUser.query();
 query.equalTo('createDate', dt);
 var items = await query.fetchAll();

**Comment by goofmint** [comment]
こちら失礼しました。2.4.1にて対応しました。アップデートをお願いします。

**Comment by goofmint** [comment]
なお、今日の日付ということであれば現在時刻のnowを使うとうまく結果が出ないかも知れません（現在時刻が入ってしまうので）。

```dart
var now = DateTime.now();
var dateOnly = DateTime(now.year, now.month, now.day);
```

のようにして、 `greaterThanOrEqualTo` を使ってください。

**Comment by S-Kaneko-5517** [comment]
早速の対応とアドバイスありがとうございました。

2.4.1にアップデートして、正常に処理を実行できました。

回答いただいたコード内では、equalToを使用しておりますが、greaterThanOrEqualToの間違いでしょうか？
equalToで実行したところ、データを抽出できなかったので。

権限の確認のアドバイスありがとうございます。また悩んでしまうところでした。

**Comment by goofmint** [comment]
すみません、更新しました！

**Comment by S-Kaneko-5517** [comment]
対応いただきありがとうございました。
大変助かりました。
