### ISSUE TITLE
monaca × ncmbのプッシュ通知でアンインストールされた端末のエラーが出ない

### ISSUE THREAD

**Issue by nobunobu123** [NIFCLOUD-mbaas/UserCommunity#1311]
プッシュ通知が現在何件届けることかできるのかを計測したく、installationから算出しようと考えています。

アンインストールされたものは省きたいと考えております。

そこで、調べてみたところ。
https://mbaas.nifcloud.com/doc/current/common/dev_guide.html
上記によると、プッシュ通知が届けられなかった場合APNsからエラーが返ってきて、自動でinstalltionsから削除されるとのことでした。

しかし、試しに私のiphone端末のアプリをアンインストールしてプッシュ通知を送ってもみても、エラーが出ず配信済みとなります。（もちろん、iphoneには通知は来ていません。）

アプリをアンインストールした端末を、installtionから削除したいのですが、どうすればよろしいでしょうか。

**Comment by goofmint** [comment]
削除はリアルタイムではなかったはずです。何回か送っている内にエラーが重なり、削除されます。

アプリを削除した際にイベントを実行できる訳ではないので、何かできる訳ではありません。

**Comment by nobunobu123** [comment]
リアルタイムではないということは、
ということは、何回か送っているうちにinstalltionsから消えていたという感じで待つしかなさそうですね。

リアルな現在のプッシュ通知受信者数を知るということはできなさそうですね。

迅速な回答ありがとうございました！
