### ISSUE TITLE
スクリプト機能の仕組みについて

### ISSUE THREAD

**Issue by Taro7x3** [NIFCLOUD-mbaas/UserCommunity#1312]
現在、自身が開発しているソフトウェア（C#）にPayPay決済機能を追加したいと思い、導入作業を行っています。
そこでいくつか問題があるため質問させていただきます。

**1、requireについて**
PayPayのAPIは計6つの node.js モジュールが存在し、互いに require で参照しています。
ローカル環境では node.js では同じフォルダ階層のモジュールを require('./example') で取得可能ですが、ニフクラではエラーが発生しました。これは仕様でしょうか？

**2、利用可能なライブラリについて**
必要なライブラリがある場合、運営様にそのライブラリの導入をしていただくことは可能でしょうか？

**3、C#用NCMB SDK（非公式）(https://blog.mbaas.nifcloud.com/entry/2020/07/28/143141) について**
現在こちらのSDKを利用して NCMBスクリプト機能へのアクセスを試みていますが、
スクリプト機能用のメソッドの説明が無かったのでGitHubにて調べたところ、
NCMBRequestクラス（https://github.com/NCMBMania/ncmb_xamarin/blob/master/src/NCMBClient.Xamarin/NCMBRequest.cs）の Exec 関数がその機能ではないかと推測しました。

Exec 関数では、

```js
var s = new NCMBSignature(NCMBRequest._ncmb.ApplicationKey, NCMBRequest._ncmb.ClientKey);
            s.Method = Method;
            s.Name = Name;
            s.ObjectId = ObjectId;
            s.Queries = Queries;
            s.Path = Path;
```

が必要であり、

Method: POST/GET/DELETE/PUT
Path: NCMBの利用する機能

であることは分かりましたが、それ以外が何で使われているのかが分かりませんでした。

これらは何のための変数なのかご教授いただけますでしょうか？
また、スクリプト機能へアクセスする際に必要な情報はあるのでしょうか？

非公式であることは承知ですので、もしお答えできない場合は構いません。

以上のほどよろしくお願い致します。

**Comment by goofmint** [comment]
1、requireについて

はい、こちらは不可となります。

2、利用可能なライブラリについて

要望があれば確認の上、追加可能です。その場合はここではなく、サポートへお問い合わせください。

現状は以下の通りです。

https://mbaas.nifcloud.com/doc/current/script/reference_nodejs.html#%E5%AF%BE%E5%BF%9C%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA

3、C#用NCMB SDK（非公式）

現状スクリプトには対応していません…（スクリプトはエンドポイントURLが異なります）ご要望があれば、なるべく早めに対応します！

まずは必要なライブラリについて、サポートへ問い合わせてみるのをお勧めします！

**Comment by Taro7x3** [comment]
早速のご回答ありがとうございます。

C#で現在ソフトウェアを構築しており、どうしても.NET環境からNCMBのスクリプト機能へアクセスしたいと考えておりますので、ご検討のほどよろしくお願い致します。

また、ライブラリに関しても一度問い合わせてみます。

ありがとうございました！

追記）中津川さんの対応早すぎてビックリしました笑 今後ともお世話になるかと思います。よろしくお願い致します。

**Comment by goofmint** [comment]
遅くなりましたがXamarin（C#） SDKにてスクリプトに対応しました。

[NCMBのC#（Xamarin） SDKがスクリプト実行に対応しました - Qiita](https://qiita.com/goofmint/items/42986286dccf2ed0a7de)

**Comment by Taro7x3** [comment]
ただいま確認致しました！
本当に助かります。ありがとうございます！
開発が進みそうです😊
