### ISSUE TITLE
【Unity】ホーム画面にログインしているユーザー名を表示させたい（その他色々）

### ISSUE THREAD

**Issue by utr411** [NIFCLOUD-mbaas/UserCommunity#1316]
### 【Unity】ホーム画面にログインしているユーザー名を表示させたい
そのような機能があったら教えていただきたいのですが、（あったらすみません）Unity SDKを利用して、RPG的なものを作りたいと思っているのですが、ログインしているユーザー名などをホーム画面に載せたいのですができるでしょうか？
また、ログインしている場合は値を１、していないばあいは、０などと出力できるでしょうか？
**【作りたい機能】**（増える可能性大）

- ユーザー名表示
- ユーザーごとのレベル、ライフなどの情報
- このドアを開けたか
- 経験値ランク（これはチュートリアルを見て完成済み）

詳細
Unity 2020.1.15f1
出力：WebGL

**Comment by utr411** [comment]
もし、このサービスの方がいいよなどのコメントありましたら教えて欲しいです

**Comment by goofmint** [comment]
厳密でなくとも良いのであれば、何かイベントを実行するたびにユーザー名を記録していくクラスを作るのが良いかと思います。

https://mbaas.nifcloud.com/doc/current/datastore/basic_usage_unity.html#%E3%83%87%E3%83%BC%E3%82%BF%E6%93%8D%E4%BD%9C

AddUniqueToListを使って、ユーザー情報を記録していけば良いかなと。ユーザーのobjectIdさえ記録しておけば、他の情報（ユーザー名、レベルなどの情報）は別途取得できるかと思います。

**Comment by utr411** [comment]
へっ。。。返信早い！？
ありがとうございます！
すみません。。。言いにくいのですが少し教えてもらうことできますでしょうか（初心者でして）

**Comment by goofmint** [comment]
ここは質問に対して回答する場になります。何が分からないのか、何を行ってどんなエラーが出たのかなどが分かれば回答することはできるかと思います。

質問は1つずつでお願いします（他の方にとっても役立つように）。新しいIssueを作成して、そこで質問していただければ。

初心者かどうかはあまり関係がないかと…。まず試した上で何がしたくて何を行ったのか、どういった問題があるのかなどを明確にしてもらえると、適切な回答が得られるかと思います。ゲーム開発、頑張ってください！
