### ISSUE TITLE
Gmailにパスワード再発行メールが届かない

### ISSUE THREAD

**Issue by min-tam** [NIFCLOUD-mbaas/UserCommunity#1326]
RestAPIにてパスワードを再発行するためのメールを送信するHttpリクエストを送信しているのですが、
メールアドレスがGmailだとメールが届かない事象が発生しています。
迷惑メールフォルダ内も確認しましたが、こちらにも届いていませんでした。

Gmailではないメールアドレスであればパスワード再発行メールが届いているようなのでAPI実行は問題ないように思います。
また、管理コンソールのREST APIツールからも同様のAPIを実行したのですが、
Gmailはメールが届かず、Gmailでないメールアドレスであればメールが届く結果となっております。

Gmailにもパスワード再発行メールが届くようにしたいのですが、対処方法をご存知の方がいれば教えていただけないでしょうか？

実行したAPIは以下になります。
```
https://mbaas.api.nifcloud.com/2013-09-01/requestPasswordReset
curl -X POST \
 -H "X-NCMB-Application-Key: xxx" \
 -H "X-NCMB-Timestamp: xxx" \
 -H "X-NCMB-Signature: xxx" \
 -H "Content-Type: application/json" \
 -d '{"mailAddress":"xxx"}' \
```

**Comment by goofmint** [comment]
Fromを設定で変えているということはありますか？試した限り、私のGmailアカウントにはメールが届きました（受信箱に）。

**Comment by min-tam** [comment]
ご回答ありがとうございます。
メール設定でアドレスを変えていたことが原因でした。

**Comment by MonacaSommelierOsaka** [comment]
> Fromを設定で変えているということはありますか？試した限り、私のGmailアカウントにはメールが届きました（受信箱に）。

原因は管理画面での送信元のメールアドレスのドメインが「mbaas.nifcloud.com」以外であることで
Gmailが届いてませんでした。

ただ、運用上「mbaas.nifcloud.com」以外のドメインを使いたいとのことですが、
具体的な対処方法はサポートに問い合わせたほうが良いでしょうか？

**Comment by goofmint** [comment]
そうですね。サポートにお問い合わせをお願いします。できそうなことというと、ドメイン側でのSPFレコード設定くらいだと思いますが…

**Comment by goofmint** [comment]
https://github.com/NIFCLOUD-mbaas/UserCommunity/issues/947

こちらに同種の質問があります。SPFレコードだけしか設定できないはずですが。
