### ISSUE TITLE
管理者によるユーザーのパスワード管理

### ISSUE THREAD

**Issue by akiaki2020** [NIFCLOUD-mbaas/UserCommunity#1330]
現在ユーザーのパスワード管理について調べています。
確認したいこととしては、
管理者がユーザーのパスワードを知りえる方法がないことを調べてます。
（下手にパスワードを知ってしまうとセキュリティ問題等が発生すると考えてるからです）

1
管理画面の会員管理について質問です。
ユーザーパスワードはHIDDENの状態ですが、これは解除できないという認識でよろしいでしょうか？
またハッシュ値で暗号化などされていますか？
＋
もしドキュメント等があればURLもお願いします

2
クエリについて質問で
REST APIやスクリプト等でパスワードを確認する方法はない認識でよろしいでしょうか？

**Comment by goofmint** [comment]
1. はい、解除できません（通信データにも入っていません）。また、暗号化されています。必要があればテクニカルサポートへお問い合わせください（有料ユーザー向けになります）。

2. パスワードを確認する方法はありません

**Comment by akiaki2020** [comment]
ご回答ありがとうございます。
