### ISSUE TITLE
ニフクラのファイルストアでcssファイルを管理

### ISSUE THREAD

**Issue by nomori7010** [NIFCLOUD-mbaas/UserCommunity#1331]
ニフクラのファイルストアにcssファイルを置いておき、それらをMonacaアプリ内で参照させてアプリの見栄えを制御することはできますか。

**Comment by goofmint** [comment]
はい、できると思います。

**Comment by nomori7010** [comment]
どのような方法になりますでしょうか。

**Comment by goofmint** [comment]
すみません、質問の意味がよく分からないのですが…。ファイルストアにCSSファイルを置いて、それをHTMLから参照すれば良いのかな、と。

https://mbaas.nifcloud.com/doc/current/filestore/contents-delivery.html

**Comment by nomori7010** [comment]
こちらのドキュメントを見落としていました。ありがとうございます。解決いたしました。
