### ISSUE TITLE
【monaca】データストアからnull以外の文字列の値を1つ取得したい

### ISSUE THREAD

**Issue by littleflower417** [NIFCLOUD-mbaas/UserCommunity#1354]
題にあるように、DBからnull以外の文字列の値を1つ取得したいです。
前提として、文字列やobjectIdの値はわからない状態です。
DBは下記の画像のようにランダムに値とnullが設定されてあります。
![DBキャプチャ](https://user-images.githubusercontent.com/127968007/228985311-79106937-12e8-4b4c-921f-4a93872913bc.PNG)

補足として、取得した値の部分にはnullを入れて、減っていくようにしたいと思っています。

**Comment by goofmint** [comment]
> DBからnull以外の文字列の値を1つ取得

ここの内容がよく分かりません…1つ取得したいというのは、1レコード取得したいということでしょうか？

**Comment by littleflower417** [comment]
迅速なご対応ありがとうございます！
nullを文字列にし、notEqualToでnullを指定したら、1レコード取得することが出来ました。

上手くお伝えできなくて、すみません。
1レコードではなく、serialの文字列の値です。
上記の画像で言うと、「a」か「b」になります。

**Comment by goofmint** [comment]
それは普通に `get` とかMapへのアクセス `['fieldName']` で、というでしょうか？

**Comment by littleflower417** [comment]
はい、そうです。

console.log(DBを入れた変数)だと、aclやobjectIdなどの他の情報も出力してしまいます。

**Comment by littleflower417** [comment]
console.log(DB変数.フィールド名)で出力することが出来ました！
ありがとうございました。
