### ISSUE TITLE
installationsの全件取得ができない

### ISSUE THREAD

**Issue by Komainu-kun** [NIFCLOUD-mbaas/UserCommunity#1356]
https://mbaas.nifcloud.com/doc/current/rest/push/installationSearch.html を参考に配信端末のオブジェクトの情報(installation)を全件取得しようとしています。
https://mbaas.api.nifcloud.com/2013-09-01/installations へアクセスしても100件分のデータしか返ってきません。
現在、installationは約1万件ほど登録がある状態です。

https://mbaas.api.nifcloud.com/2013-09-01/installations?limit=100000  とすると返ってくるデータ量が1000件になりますが全件取得とはなっていません。
全件取得するにはどのようなAPIを実行したらよいのでしょうか。

**Comment by goofmint** [comment]
データストアなど（Installation含む）はマックス1000件までしか取得できません。skipと組み合わせて複数回実行してください

**Comment by Komainu-kun** [comment]
ご回答ありがとうございます。
1度に取得できる件数に制限があるんですね。
ループで全件取得するようにします。
