### ISSUE TITLE
カレントユーザーの現在のポイント表示ができません

### ISSUE THREAD

**Issue by taigabamu** [NIFCLOUD-mbaas/UserCommunity#1361]
Monaca でスマホアプリを作成しています。
ユーザーが新規登録した際に、獲得ポイントを保存するためのDBも同時に作成するコードをかきました。
ログインしたら、ユーザー名とポイント数を表示させたいのですが、ポイント数の表示ができません。
どうか、ご助言をいただきたいです。
よろしくお願いいたします。　Monacaのテンプレはonsenuiを使用しています。

※コードは下に書き直しました。

このコードで実行すると「ポイントデータが見つかりませんでした」となります。
会員管理とポイント管理用の「PointData」クラスは正常に作成されています。
コンソールは以下の通りです。
新規ユーザー登録成功
index.html:3 ポイントデータ作成成功:{"user":{"__type":"Pointer","className":"user","objectId":"ieWfN1EFKy2iPd3U"},"points":0,"createDate":"2023-06-08T08:28:42.064Z","objectId":"4a6ZSlaY6B10s7Ng"}
index.html:3 ログイン成功:{"userName":"ああああああああ","password":"123456789","createDate":"2023-06-08T08:28:41.606Z","objectId":"ieWfN1EFKy2iPd3U","sessionToken":"iABRpglvQ2k3gdFZoHQPGbVi6","authData":null}
index.html:3 ポイントデータが見つかりませんでした。

**Comment by goofmint** [comment]
@taigabamu 全体を追うのは無理なので、他の人が見て分かる最低限のコードにしてください

**Comment by taigabamu** [comment]
解決しました
