### ISSUE TITLE
APNsのフィードバックによるデバイストークンの削除について

### ISSUE THREAD

**Issue by odapivot** [NIFCLOUD-mbaas/UserCommunity#243]
nifty mbaasでは、APNsのフィードバックサービスをもとに、通知が届かなくなったデバイストークンの削除を定期的におこなっていると思いますが、これはどのくらいの頻度で行っていますでしょうか？

前提として、外部のDBにて、オブジェクトIDもしくはデバイストークンと会員情報を紐づけて、セグメント配信を考えており、無効になったデバイストークンの消しこみを外部DBにも行うことを考えています。

**Comment by moongift** [comment]
@odapivot 

中の人に聞いたところ、配信を行ったタイミングでエラーとなったトークンを消しているそうです。そのためプッシュ通知を行わないと消去処理は行われません、とのことです。

**Comment by odapivot** [comment]
回答ありがとうございます。

配信を行ったタイミングのエラーレスポンスでトークンを消しているとこのことですが、
ユーザーがアプリをインストールしている状態で、push通知をoffにしている場合は、
エラーにはならず、トークンは削除されないという認識であっていますでしょうか？

ユーザがpush通知をOFFにしたタイミングで通知した場合に、トークンが削除されて、
その後ユーザーがpush通知ONにしたあとに、通知が届かなくなることを懸念しています。

**Comment by odapivot** [comment]
すいません。こちら自己解決いたしました。

push通知をOFFにしたタイミングで通知した場合に、トークンは削除されない。

**Comment by odapivot** [comment]
クローズしていなかったので、クローズします。
