### ISSUE TITLE
Monacaからのアクセス時にOrigin is not allowed by Access-Control-Allow-Originが発生

### ISSUE THREAD

**Issue by tatematsu-k** [NIFCloud-mbaas/UserCommunity#281]
質問失礼します。

MonacaとNifty mobile backendのサービスを利用してアプリ開発をしようとしています。
現在Monacaのほうからデータストアにアクセス(登録・検索・変更・削除)をしようとするとOrigin is not allowed by Access-Control-Allow-Originというエラーが発生します。
しかし、データストアのアクセスも5～7回に１回程度正常に動作しています。
SDKはインポートしています。

まだ始めたばかりでずっとこの調子なので最初に何か設定が必要なのではないかと考えています。
ご存知の方がいらっしゃいましたらご教授のほどよろしくお願いいたします。

**Comment by moongift** [comment]
データストアのアクセスが時々エラーを起こすといった症状なのでしょうか？
