### ISSUE TITLE
 DoneCallback()に代わるクラスを教えてください。

### ISSUE THREAD

**Issue by whitepotato** [NIFCLOUD-mbaas/UserCommunity#319]
ドキュメントを見ながら、仮実装をしているのですが、
クラス名やメソッド名が実際のものと違いすぎて困惑しています。。
DoneCallback()に代わるクラス名を押してください。

//NCMBUserのインスタンスを作成
NCMBUser user = new NCMBUser();

//ユーザ名を設定
user.setUserName("YOUR_USER_NAME");

//パスワードを設定
user.setPassword("YOUR_PASSWORD");

//設定したユーザ名とパスワードで会員登録を行う
user.signUpInBackground(new DoneCallback() {
    @Override
    public void done(NCMBException e) {
        if (e != null) {

```
        //会員登録時にエラーが発生した場合の処理
    }
}
```

});

**Comment by moongift** [comment]
import com.nifty.cloud.mb.core.DoneCallback;
import com.nifty.cloud.mb.core.NCMB;
import com.nifty.cloud.mb.core.NCMBException;
import com.nifty.cloud.mb.core.NCMBObject;
import com.nifty.cloud.mb.core.NCMBUser;


ここら辺のインポートがないのが原因のようです。

**Comment by whitepotato** [comment]
最新のバージョンだと、ネームスペースに"core"はないようなのですが？？
（ちなみにAndroid版です。）
import com.nifty.cloud.mb.NCMB;
import com.nifty.cloud.mb.NCMBException;
import com.nifty.cloud.mb.NCMBObject;
import com.nifty.cloud.mb.NCMBUser;
