### ISSUE TITLE
パスワードのリセット方法（Monaca with Nifty Cloud mobile backend）

### ISSUE THREAD

**Issue by messhiida** [NIFCloud-mbaas/UserCommunity#514]
パスワードのリセット方法について、下記を参考にしてみたものの、どうも関数が実行されないようでした。
http://mb.cloud.nifty.com/doc/current/sdkguide/javascript/user.html#パスワードのリセット

実行環境はMonaca cloud IDE、クラウド上のデバッガーでテストしています。
SignupByAccountなどは関数として実行されるのですが、
上記のresetPasswordおよびSignupwithemailなどは実行されませんでした。。。
何かloadなどが必要でしょうか？

**Comment by moongift** [comment]
コードが間違っていたようです。こちらのコードでいかがでしょう？

```
var user = new ncmb.User();
user.set("mailAddress", "mail@abc.com");
user.requestPasswordReset()
  .then(function(data){
    // 送信後処理
    console.log("送信完了");
  })
  .catch(function(err){
    // エラー処理
    console.log("送信失敗");
  });
```

**Comment by messhiida** [comment]
ありがとうございます！こちらで解決致しました。
