### ISSUE TITLE
データストアの値をインクリメント

### ISSUE THREAD

**Issue by tatane616** [NIFCLOUD-mbaas/UserCommunity#805]
android studioでアプリを制作しており、アプリ側からの操作でデータストアの値をインクリメントしたいと思っています、 そこで次のようなプログラムを書いたのですが最後の行だけエラーが出てしまいUnhandled exception: com.nifty.cloud.mb.core.NCMBExceptionと表示されます。
`NCMBObject obj = new NCMBObject("TestClass");
  obj.setObjectId("getTestObjectId");
  obj.increment("key", 1);`
解決方法をご存知の方いらっしゃいましたらお願いいたします。

**Comment by sunnytj39** [comment]
try catchで例外処理をすることで解決しました。

**Comment by goofmint** [comment]
increment はすでにデータと該当キーのデータが存在する場合のみ使えるメソッドになります。
