### ISSUE TITLE
[無償プラン]突然、1000台以上に対し、Push通知が飛ばなくなった

### ISSUE THREAD

**Issue by dokurocker** [NIFCloud-mbaas/UserCommunity#825]
お世話になります。

ブログビューアアプリを開発し、運用を行なっています。

ブログに記事が投稿された際、ブログのサーバー側でRestAPIを叩き、
記事のタイトルを、全端末に対しPush通知を行なっています。

この仕組みで、数ヶ月問題なく運用を行なっていたのですが、
12/5 15:01頃、1423端末に対し、Push通知が行われたのですが、
12/5 16:31頃（次の記事）、284端末しか、Push通知が行われていませんでした。

通知対象端末が1000台以上減ってしまいました。
この1時間半の間、特にデータの操作は行なっていません。

このように、突然、対象端末が減るという原因は、何が考えられるでしょうか？
（無償プランということが何か関連してるのでしょうか？）

また、復旧方法、回避方法があればご教授ください。

以上です。
よろしくお願いいたします。

**Comment by dokurocker** [comment]
追記です。
Push通知が飛ばなくなったのは、iOS端末になります。
Installationクラスからレコードが消えたようです。

**Comment by goofmint** [comment]
プランは特に関係ありません。Installationクラスからデータがなくなる要因としては、アプリアンインストールなどに伴うプッシュ通知の配信エラーになったデータ自動削除が考えられます（後は管理画面からの手作業での削除でしょうか）。これはエラーになっているトークンなので復旧する方法はありません。

**Comment by dokurocker** [comment]
早速のご返答ありがとうございます。

ご返答を受け、
12/5 〜16:32（問題が発生するまで）のプッシュ通知で
「ステータス：配信エラー」でフィルタをかけたのですが、
1000端末以上で配信エラーとなっているプッシュ通知はありませんでした。

ドキュメントを見返しつつ、原因や回避策を考えてみます。

ありがとうございました。

**Comment by goofmint** [comment]
配信エラーの場合、トークンが不正といったものになります。届かない（送信自体はOKで、後でエラーが確認できる）場合は管理画面で確認できない覚えがあります。

**Comment by dokurocker** [comment]
なるほど、ありがとうございます。
でしたら、届かなくてInstallationが自動削除されたのは、十分考えられますね。

今回対象が約1000端末のiOSでしたが、
一斉にアンインストールされるというのは考えにくいので、
APNsの都合で通知が届かなかったのかな？と推測しているのですが、
その可能性って考えられますでしょうか？

**Comment by goofmint** [comment]
一斉にアンインストールはないと思います。mBaaS側の反映がバッチ処理というのは聞いたことがありますので、そのせいだと思います。APNs側の都合というのはないかなと…。

**Comment by dokurocker** [comment]
かしこまりました。
ご回答ありがとうございました！
