### ISSUE TITLE
スクリプトでのプッシュ登録とjsonの扱いについて

### ISSUE THREAD

**Issue by kiripeace** [NIFCloud-mbaas/UserCommunity#826]
現在別サーバー上にあるjsonファイルを見にいき、中身のメールアドレスとinstallationに登録してあるアドレスが一致したらプッシュを登録したいと思っています。

requireで読み込むところまではなんとかわかるのですがそれ以降まったく進まない状況です。。
ふわっとした質問で申し訳ないですが、どなたか回答していただければと思います。

**Comment by goofmint** [comment]
今の情報だけだとなかなかアドバイスしづらいですね…。とりあえず言語はJavaScriptでしょうか？処理的には次のようになりますか？

1. リモートのJSONファイルを取得する
2. JSONファイルに記述されているメールアドレスを使ってmBaaSのInstallationを検索
3. 一致するデータがあればプッシュ通知を登録

**Comment by kiripeace** [comment]
ご回答ありがとうございます！

わかりにくい質問で申し訳ありません。
その通りです！

**Comment by goofmint** [comment]
やり方としては Installation にカラム（例えば email）を追加してメールアドレスを保存します。

後はPushを作る時の検索条件に指定すればOKです。

```js
ncmb.Push
  .set('title', 'タイトル') // プッシュ通知の内容
    : // その他の条件
  .set('searchCondtion', {email: email}) // メールアドレス
  .send()
  .then((push) => {
    // 処理成功した場合
  })
  .catch((err) => {
    // エラーの場合
  });
```

searchConditionで指定すればInstallationでマッチするデータに対してプッシュ通知を配信してくれます。事前に検索する必要はないかと思います（データがなければ別な処理をする、といった場合は必要ですが）。

**Comment by kiripeace** [comment]
回答ありがとうございました。
解決致しました。
