### ISSUE TITLE
管理画面のデータストアのフィールドの並び変え

### ISSUE THREAD

**Issue by suzuhiroruri** [NIFCloud-mbaas/UserCommunity#829]
管理画面のデータストアのフィールドの並び変えはできますか??

**Comment by goofmint** [comment]
残念ながらないですね…。一応希望として前に中の人に伝えたことはあります。

**Comment by suzuhiroruri** [comment]
@goofmint
コメントありがとうございます。
そうなんですね。 。
後からフィールド追加することも多いですが、後から追加するだけあって必須データでは無いのですが、
一覧で先頭に来るのがどうもしっくりこなくて....
