### ISSUE TITLE
データエクスポートできない

### ISSUE THREAD

**Issue by suzuhiroruri** [NIFCloud-mbaas/UserCommunity#834]
タイトルの通りです。
エクスポートできなくて困ってます。
以前はエクスポートできたのですが、現在できなくなってます。
ご存知の方いらっしゃいましたら、教えていただきるとありがたいです。

**Comment by goofmint** [comment]
http://info.biz.nifty.com/mb/2018/01/post-72.html

これじゃないかと思います。10日間…長いですね…。

**Comment by suzuhiroruri** [comment]
@goofmint 
なるほど〜
ありがとうございます！
