### ISSUE TITLE
ACL設定したファイルの閲覧

### ISSUE THREAD

**Issue by matutoshi** [NIFCloud-mbaas/UserCommunity#850]
お世話になります。情報サイトを作成していまして、一般会員とプレミアム会員を区別し、プレミアム会員は一般会員コンテンツ ＋ 限定のコンテンツにアクセスできるようにしたいと思っています。
Issuesの #551 で同じような質問があったのですが、goofmintさんが回答されている「何か適当なHTMLを読み込んで、その中でJavaScript SDKを使ってHTMLコンテンツを取得し、その内容をHTML中に埋め込む」という具体的な方法がいまいち理解できずに詰まっているのでご教授いただけますと幸いです。
もしくは上記を実現するのに他に良い方法などありますでしょうか？当方開発経験がなく、無知で申し訳ありませんが、よろしくお願い致します。

**Comment by goofmint** [comment]
インターネットで公開されているWebサイト上でJavaScript SDKを使うとクライアントキーを公開しないといけないので良くないかと思います。サーバサイドで取得する分には問題ありません。

その上で、ですが。認証後に `ncmb.File.download` を使えばプレミアムコンテンツにアクセスできるようになります。

[ファイルストア (JavaScript) : 基本的な使い方 | ニフクラ mobile backend](http://mb.cloud.nifty.com/doc/current/filestore/basic_usage_javascript.html#%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AE%E4%B8%AD%E8%BA%AB%E3%82%92%E5%8F%96%E5%BE%97)

**Comment by matutoshi** [comment]
早速のご返信ありがとうございます。試してみます。

**Comment by matutoshi** [comment]
度々恐れ入ります。アップロードしたファイルとカレントユーザーに「premium」というロールを設定し、ログインした後のhtmlファイルに下記のように記述しています。
<script>
//まだテスト段階なのでキーをhtml内に記述しています。
  var ncmb = new NCMB("アプリケーションキー","クライアントキー");

function getPre(){
　ncmb.File.download("アップロードしてあるファイル名")
    .then(function(fileData){
	location.replace('公開ファイルURL')
     })
    .catch(function(err){
      alert('error')
     });
}
</script>
<button onclick="getPre()">pre only</button>

ボタンをクリックするとエラーのアラートが出てしまいます。location.replaceの引数をファイル名に変えても同じ状態なのですが、どこを修正すればよろしいでしょうか？
お手数ですがよろしくお願いします。

**Comment by matutoshi** [comment]
``

**Comment by matutoshi** [comment]
データストアにロールを作成してリレーションすればいいと思っていましたが、加えて個別のロール設定をしたら動作しました。失礼しました。
