### ISSUE TITLE
Monacaプラグイン Androidのダイアログ表示について

### ISSUE THREAD

**Issue by dyoshikawa** [NIFCLOUD-mbaas/UserCommunity#898]
https://mbaas.nifcloud.com/doc/current/push/dialogpush_monaca.html

> Monacaプラグインでは、ダイアログ表示に対応していません。
> Android向けにプッシュ通知を配信した場合は通常の表示になります。

とのことですが、当方、ダイアログ表示の必要性があり、カスタマイズを加えることでAndroidダイアログ通知に対応したのですが、需要があるようでしたらPR送る等考えております。
如何でしょうか？

**Comment by goofmint** [comment]
ぜひこちらにお寄せください！

https://github.com/NIFCloud-mbaas/ncmb_android
