### ISSUE TITLE
FCMへの移行について

### ISSUE THREAD

**Issue by kasonen** [NIFCloud-mbaas/UserCommunity#921]
FCMへの移行テスト中なのですが、ダッシュボードから通知を配信すると
テスト中のバージョンの端末のみ通知エラーとなってしまいます。
tooManyTopicsというエラーなのですが、原因はどこにあるのでしょうか。

通知内容はタイトル・メッセージなど全て空の通知でも同様のエラーが発生します。

```
{
    "android": {
        "total": 11,
        "tooManyTopics": 1,
        "complete": 10
    },
    "description": {
        "status": "complete"
    }
}
```

**Comment by komiyama-camelot** [comment]
当方でも同様の症状となっており、動作確認が出来ておりません。
APIから送信しても同様の結果となっております。

現在はデバイストークンを使用して FCM の API から直接送信してSDKの動きを確認している次第です。

**Comment by goofmint** [comment]
原因がいくつかあって、きちんと分かっていないようなのですが。一番有力なのはFCMでFirebase Cloud Messaging APIを有効にしていない場合らしいです。こちら、コンソールで確認してもらえますか？

![screenshot_ 2018-09-06 11 07 28](https://user-images.githubusercontent.com/5709/45210014-6eb00480-b2c9-11e8-8add-59cb5ee14078.png)

**Comment by kasonen** [comment]
確認したところ、APIが無効になってまして、有効にしたら解決しました。ありがとうございます。

移行ドキュメントを見ただけでは移行できなくて四苦八苦しました。

**Comment by goofmint** [comment]
新規で作るとデフォルトで有効になっているらしく…すみません！また何かあったらご質問ください！
