### ISSUE TITLE
mBaaSとPusherを使ってチャットアプリを作る、１～４やってみたが通知が来ない

### ISSUE THREAD

**Issue by kasaishouhei** [NIFCloud-mbaas/UserCommunity#930]
ＭｏｎａｃａＤｅｂｕｇｇｅｒを使って初めてチャットアプリを開発していますが
ncmb.Script.data(,,,,,).exec("post", "push.js")のところで、Ｕｎａｕｔｈｏｒｉｚｅｄのエラーがでます。
そもそも仕組みとしてＤｅｂｕｇｇｅｒの通知は送れませんか？
それとも他に問題がありそうですか？
ちなみにその前に、警告で
The SSL certificate used to load resources from https://script.mb.api.cloud.nifty.com will be distrusted in the future. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
が出ます。

**Comment by goofmint** [comment]
まずJavaScript SDKを最新版にした方が良いかと思います。

**Comment by goofmint** [comment]
Unauthorizedが出たところのコードを見ることはできますか？後、push.jsの内容も知りたいです。

**Comment by kasaishouhei** [comment]
これがPusher.jsで
const crypto  = require("crypto");
const request = require('superagent');
const NCMB    = require('ncmb');
module.exports = (req, res) => {  
    const applicationKey = '09edexxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
    const clientKey = '3f3e2exxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
    saveDataStore(
        applicationKey,
        clientKey,
        req.body
    ).then(() => {

        return sendPusher(
            'f5xxxxxxxxxxxxxxxxx',
            '5xxxxxxxxxxxxxxxxxx',
            '5xxxxxxx',
            req.body
        )
    })
    .then((response) => {
        res.json({});
    })
    .catch((err) => res.status(401).json(err));
};

const saveDataStore = (applicationKey, clientKey, body) => {
    const ncmb = new NCMB(applicationKey, clientKey);
    const Chat = ncmb.DataStore('Chat');
    const chat = new Chat;
        return chat
        .set('chatid', body.chatid)
        .set('touser', body.touser)
        .set('message', body.message)
        .save()
}

const sendPusher = (authKey, secretKey, appId, body) => {
    const authTimestamp = Date.now() / 1000;
    const authVersion = '1.0';
    const medhod = 'POST';
    const path = `/apps/${appId}/events`;

    const message = {
        data: JSON.stringify({
            touser: body.touser,
            message: body.message
        }),
        name: "message",
        channel: body.chatid
    };

    const bodyMd5 = crypto
        .createHash('md5')
        .update(JSON.stringify(message))
        .digest('hex');
    const queryString = `auth_key=${authKey}&auth_timestamp=${authTimestamp}&auth_version=${authVersion}&body_md5=${bodyMd5}`;
    const authSigning = [
        medhod,
        path,
        queryString
    ].join("\n");
    const signature = crypto
        .createHmac("SHA256", secretKey)
        .update(authSigning)
        .digest("hex");
    return request
        .post(`https://api.pusherapp.com${path}?${queryString}&auth_signature=${signature}`)
        .set('Content-Type', 'application/json')
        .send(JSON.stringify(message))
}

これがUnauthorizedが出たところのコードのコードです。
function send() {
  const message = $('#message').val();
  //いる？
  currentLoginUser = ncmb.User.getCurrentUser();
  //1
  const touser =  currentLoginUser.get("objectId");
  console.log( touser + "メッセージ送信 自分のｏｂｊｅｃｔＩｄ１");
  console.log( message + "Message1");
  const chatid  = $('#channelId').val();
  console.log( chatid + "chatｉｄ");
  ncmb.Script
      .data({
        touser,
        message,
        chatid
      })
      .exec("POST", "push.js")
      .then(function(res){
        console.log( res + "成功 この後メッセージ消えるはず");
        $('#message').val('');
      })
      .catch(function(err){
        console.log( err + "送信失敗");
      });
};

何かバグかもしくは必要な手順やライブラリの読み込みがたりてませんか？
もしくはｍｏｎａｃａＤｅｂｕｇｇｅｒでは通知を受け取れないなどの仕様とかですか？
色々試していますがうまくいきません

**Comment by kasaishouhei** [comment]
質問が多くて申し訳ないです、ちなみに
const crypto = require("crypto");
const request = require('superagent');
const NCMB = require('ncmb');
と書く以外に、ニフクラでこれらを使うときに何か手順は必要ですか？

**Comment by goofmint** [comment]
```js
const crypto = require("crypto");
const request = require('superagent');
```

はPusher側で必要なライブラリで、NCMB側では不要です。 `ncmb` だけ入っていれば基本的にOKです。

スクリプトのログはNCMBの管理画面で見られます。その際のエラーメッセージはどうなっているでしょうか。

後、データストアには期待通りに保存されているでしょうか。保存されていれば、問題はPusher側のコードにあると推定できるのですが。

**Comment by kasaishouhei** [comment]
データストアには期待通りに保存されています。

スクリプトのログは
{
  "Status": "DONE",
  "RequestHeaders": "{\"host\":\"script.mb.api.cloud.nifty.com\",\"x-forwarded-for\":\"175.184.28.160, 175.184.41.120\",\"x-forwarded-host\":\"script.mb.api.cloud.nifty.com\",\"x-forwarded-server\":\"script.mb.api.cloud.nifty.com\",\"x-real-ip\":\"175.184.41.120\",\"connection\":\"close\",\"content-length\":\"92\",\"x-ncmb-timestamp\":\"2018-10-01T16:37:41.504Z\",\"x-ncmb-signature\":\"8Uo9yWo21daNDa8qTSQFguFXL7W3Jq0mj1CtD7s62so=\",\"user-agent\":\"Mozilla/5.0 (Linux; Android 8.0.0; 701SO Build/47.1.D.11.32; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Mobile Safari/537.36\",\"content-type\":\"application/json\",\"x-ncmb-apps-session-token\":\"aBv1SjywjxCNpLUNjARqHFjLP\",\"accept\":\"text/plain\",\"x-ncmb-sdk-version\":\"javascript-2.2.2\",\"x-ncmb-application-key\":\"09ede3xxxxxxxxxxxxxxxxxxxxx\",\"origin\":\"file://\",\"accept-encoding\":\"gzip, deflate\",\"accept-language\":\"ja-JP,en-US;q=0.9\",\"x-requested-with\":\"mobi.monaca.debugger\"}",
  "RequestQuery": "{}",
  "ResponseHeaders": "{\"Content-Type\":\"application/json\"}",
  "Error": null,
  "Duration": 3136,
  "created_at": "2018-10-01T16:37:40.000Z",
  "updated_at": "2018-10-01T16:37:43.000Z",
  "ResponseStatus": 401,
  "ScriptIdentifier": "push.js"
}
で認証エラーの４０１が出ている以外に何かおかしいところはありますか？
https://g.co/chrome/symantecpkicertsは何か関係がありますかね？
かなり嵌ってます。
それから実機ビルドは通知を受け取るときは必要ですか？

**Comment by goofmint** [comment]
データが保存されているとなると、Pusher側の部分でのエラーですね。

```js
const crypto  = require("crypto");
const request = require('superagent');
sendPusher(
  'f5xxxxxxxxxxxxxxxxx',
  '5xxxxxxxxxxxxxxxxxx',
  '5xxxxxxx',
  {
    touser: "何か",
    body: "メッセージ"
  }
)
.then((response) => {
        res.json({});
})
.catch((err) => console.log(err));

const sendPusher = (authKey, secretKey, appId, body) => {
    const authTimestamp = Date.now() / 1000;
    const authVersion = '1.0';
    const medhod = 'POST';
    const path = `/apps/${appId}/events`;

    const message = {
        data: JSON.stringify({
            touser: body.touser,
            message: body.message
        }),
        name: "message",
        channel: body.chatid
    };

    const bodyMd5 = crypto
        .createHash('md5')
        .update(JSON.stringify(message))
        .digest('hex');
    const queryString = `auth_key=${authKey}&auth_timestamp=${authTimestamp}&auth_version=${authVersion}&body_md5=${bodyMd5}`;
    const authSigning = [
        medhod,
        path,
        queryString
    ].join("\n");
    const signature = crypto
        .createHmac("SHA256", secretKey)
        .update(authSigning)
        .digest("hex");
    return request
        .post(`https://api.pusherapp.com${path}?${queryString}&auth_signature=${signature}`)
        .set('Content-Type', 'application/json')
        .send(JSON.stringify(message))
}
```

といったファイルをローカルで作ってNode.jsで実行すると何かエラーが出るでしょうか？

> https://g.co/chrome/symantecpkicertsは何か関係がありますかね？

これは何でしょう？

JavaScriptだけで実装していますので、実機ビルドは不要です。

**Comment by kasaishouhei** [comment]
上記のＵＲＬはＭｏｎａｃａＤｅｂｕｇｇｅｒで警告として出ます。

（ファイルをローカルで作ってNode.jsで実行する。）とは具体的にどこで何をすればできますか？初心者で申し訳ないです。
ちなみに、ｎｃｍｂに書いて頂いたコードをアップロードして実行し、ログを取ると、Ｒｅｓｐｏｎｓｅｓｔａｔｕｓ５００が出ます。

**Comment by kasaishouhei** [comment]
ローカルにnode.jsをインストールして上記のファイルを実行したら、このエラーが出ます。
Error: Cannot find module 'superagent'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\kasai shouhei\Desktop\node-test\testpusher.js:6:17)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

ちなみにＭｏｎａｃａＤｅｂｕｇｇｅｅｒのログには
The SSL certificate used to load resources from https://script.mb.api.cloud.nifty.com will be distrusted in the future. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
が出ます。

ｐｕｓｈｅｒの自分のキーやIDはchannels appsの-developmentを使えばいいですよね？
-stagingや-productionのほうがいいですか？

**Comment by kasaishouhei** [comment]
ちなみに、クライアントで
Pusher.logToConsole = true;
にしたのですが、
Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":4001,"message":"App key xxxxxxxx not in this cluster. Did you forget to specify the cluster?"}}}
が出ます。

**Comment by kasaishouhei** [comment]
ちなみに、mobile backendのpush.js実行ログは

{"original":null,"response":{"req":{"method":"POST","url":"https://api.pusherapp.com/apps/618519/events?auth_key=4xxxxxxxxxxxxxxxx&auth_timestamp=1539685757.565&auth_version=1.0&body_md5=493xxxxxxxxxxxxxxxxxxxx&auth_signature=ea40af73bf0c0363bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","data":"{\"data\":\"{\\\"touser\\\":\\\"vbbdfbdsfbsf\\\",\\\"message\\\":\\\"何かメッセージ\\\"}\",\"name\":\"message\",\"channel\":\"xvfvfsdfregvsfv\"}","headers":{"user-agent":"node-superagent/2.3.0","content-type":"application/json"}},"header":{"content-type":"text/html;charset=utf-8","server":"thin","content-length":"17","connection":"Close"},"status":400,"text":"Unknown auth_key\n"},"status":400}

と、なります。　
Unknown auth_key status:400が気になりますが対処の仕方がわかりません。

ｍｏｎａｃａでPusher.logToConsole = true;にしてlogを追っていっても

State changed : initialized -> connecting
Pusher : Connecting : {"transport":"ws","url":"wss://ws-ap1.pusher.com:443/app/4xxxxxxx?protocol=7&client=js&version=4.3.1&flash=false"}
Pusher : State changed : connecting -> connected with new socket ID 7002.1xxxxx
Pusher : Event recd : {"event":"pusher_internal:subscription_succeeded","data":{},"channel":"XZxxxxx"}
Pusher : No callbacks on XZxxxxx for pusher:subscription_succeeded

と、connectionに問題はないと思いますが何かおかしいですか？
やはりPusherのAPI呼び出しに、push.jsのｓｅｎｄＰｕｓｈｅｒのところで何か間違っていますか？
