### ISSUE TITLE
アプリが削除されて利用不可になった場合のデータベースの復旧

### ISSUE THREAD

**Issue by hamayanhamayan** [NIFCloud-mbaas/UserCommunity#937]
いつもお世話になっております。
質問する場所を間違えていたらすみません。
Basicプランにて活用させていただいております。

https://mbaas.nifcloud.com/faq.htm の

> Q : 一定期間サービスを利用しなかった場合はどうなりますか。
> A : Basicプラン利用者が1カ月間、コントロールパネルへのログインを行わず、かつ、保有するアプリに一度もリクエストがない場合、アプリは削除されて利用不可となります。
> Expertプラン、カスタマイズプランをご利用いただいている場合は、データは削除されることはありません。

によって、自分のアプリが削除されてしまったのだと思うのですが、そのアプリのデータベースを復旧、または、データの取得を行う手段はありますでしょうか。
自分のアカウントで利用状況を確認した所、ストレージが少し使われており、まだデータが残っているのではないかと思いました。

以上です。
よろしくお願いいたします。

**Comment by goofmint** [comment]
基本、すでになくなっているようです。消されてすぐであれば、有償対応もできなくないらしいですが、詳しくはサポートに問い合わせてみてください。

ストレージはアプリを新規で作っても対象利用されるので、その分ではないでしょうか。

**Comment by hamayanhamayan** [comment]
なるほど。
承知いたしました。
ご回答いただき、ありがとうございます。
