### ISSUE TITLE
異なるアプリ間で同じファイルストアを使うことは出来ますか？

### ISSUE THREAD

**Issue by bizkit-kit** [NIFCloud-mbaas/UserCommunity#944]
こんにちは。

先日、公開しているiOS用のアプリ(有料版、無料版)にニフクラを使ってプッシュ通知をする機能を組み込んで公開しました。アプリの有料版と無料版はそれぞれ別のアプリです(中身は広告があるかないかで、同じ機能を持つアプリです)。なので、APIキーはそれぞれのアプリで取得しました。

今後、有料版・無料版の両方からアクセスできるファイル共有的な機能を、ニフクラのファイルストアを使って作って見ようと思っていたのですが、アプリを公開した後に「これってひょっとしてAPIキーが別だからそれぞれのファイルストアにしかアクセスできないのでは・・・？」と思ったのです。

有料版・無料版両方から同じファイルストアを使用することは可能なのでしょうか？

以上、よろしくお願いいたしますm(_ _)m

**Comment by goofmint** [comment]
mBaaSへのアクセスはアプリケーションキーとクライアントキーで制御しています。アプリのバンドルIDは使っていません。なので、一時的にアプリケーションキー/クライアントキーを変えて別な（mBaaS上の）アプリにアクセスできます。

ただ、プッシュ通知はバンドルIDに依存するので、無料版で登録した際のデバイストークンは有料版で使えません。

**Comment by bizkit-kit** [comment]
ありがとうございます。一時的にキーを変えたり出来るのですね。

キーを指定してSDKを初期化するコストがどれくらいかちょっと気になりました。(あまり頻繁に変えるのはよくなさそう)

今のところ、appDelegateにプッシュ通知用の処理しか実装していないのですが、一時的にキーを変えてSDKをファイルストア用に初期化した場合、プッシュ通知用に実装済みの処理にどこまで影響があるかがイマイチわからないです。

ほとんど起動時に終わってしまう様な処理なのであんまり関係ない気もするのですが、プッシュ通知の開封通知処理はひょっとすると影響がありますか？
※プッシュ通知の全貌が理解できているわけではないので、ちょっと的を外した質問かもしれません。すみません。

**Comment by goofmint** [comment]
新しいインスタンスを作っている訳ではないので、コストは殆ど発生しないかと思います。ただ、一度変更した後は、再度戻すのを忘れず行っておく必要があります。

プッシュ通知の受信については特に影響はないはずです。開封レポートを送る際にアプリケーションキーを使っていますので、キーを元に戻す処理を行っておく必要はありそうです。

**Comment by bizkit-kit** [comment]
よくわかりました。ありがとうございました！
