### ISSUE TITLE
ncmbを有効にした際の画面遷移アニメーションについて

### ISSUE THREAD

**Issue by matsu-6b** [NIFCloud-mbaas/UserCommunity#951]
monacaについて興味を持ち、こちらのサンプルアプリを参考に作ってみました。
https://github.com/natsumo/MonacaUserDemoApp
しかし、画面遷移する際のアニメーションがncmbを追加した途端に無効化されてしまいます。
なにか良い解決策はございますでしょうか？

**Comment by goofmint** [comment]
アニメーションとNCMBとは干渉し合わないかなと思うのですが…。何か別なエラーは出ていないでしょうか？

**Comment by matsu-6b** [comment]
コンソールを見る限りでは何も出ていないように見えます。
data-transition="flow"が正常に動作してくれていないようなので、それに関する記述をncmbコンポーネント内のloader.jsから探してみたところ、16315行目に
- clicks and submits should use the closing transition that the dialog opened with
unless a data-transition is specified on the link/form
- if the click was on the close button, or the link has a data-rel="back" it'll go back in history naturally
との記述がありました。
が、どのように直せばよいか分からず困っています…。

**Comment by goofmint** [comment]
`data-transition` といった表記はNCMBのJavaScript SDK内にはありません。loader.jsということは、Monacaのライブラリ読み込みライブラリではないでしょうか。

**Comment by matsu-6b** [comment]
すみませんでした。自己解決しました。
元々data-transition="fade"の記述が無かったのに適用されていたみたいです。失礼いたしました。
