### ISSUE TITLE
NIFCloudMB v3.0.1で不具合

### ISSUE THREAD

**Issue by yumen-s** [NIFCloud-mbaas/UserCommunity#963]
ncmb-push-monaca-plugin v3.0.1 を利用したところ、setDeviceTokenの動作がおかしいように感じたので、確認も含めて報告します。

[ドキュメント](https://github.com/NIFCloud-mbaas/monaca_push_plugin)では、2系と違って

- (String)applicationKey
- (String)clientKey
- (Function)successCallback() (OPTIONAL)
- (Function)errorCallback(error) (OPTIONAL)

を引数に渡すように変更されています。(senderIdの指定が不要になっているようです)

以下は今回実行したソースコードの抜粋です。
```
# index.html

<head>
  <script>
  document.addEventListener("deviceready", () => {
    const appKey = "MY_APPLICATION_KEY";
    const cliKey = "MY_CLIENT_KEY";

    window.NCMB.monaca.setDeviceToken(appKey, cliKey,
      () => { alert("success") },
      e => { alert(JSON.stringify(e)) },
    );
  });
  </script>
</head>
```

以下のエラーを確認しました。
`TypeError: Wrong type for parameter "senderId" of NCMB.monaca.setDeviceToken: Expected String, but got Function.`

senderIdを渡すところが文字列ではなく関数になっている という内容だと思います。
第3引数に文字列を渡すとエラーは出なくなりましたが、指定したコールバックはどちらも実行されず、データストアのinstallationクラスには何も登録されませんでした。

**Comment by goofmint** [comment]
内部で確認したところ、3.0.1での正常動作が確認できました。

旧バージョンを使っていてバージョンアップする場合、プラグインを削除して追加しても適用されないケースがあるようです。ドロップダウンで選択してみてもらえますか？（旧バージョンを使っていなかったら違う原因だと思いますが…）

**Comment by yumen-s** [comment]
今更ではありますが、他のプロジェクトで問題なく動作しました。原因はわかりませんでしたが（おそらく手順のミス等かと思います..）とりあえず解決はしたので閉じさせていただきます。
