### ISSUE TITLE
Android SDKでのデータストアの登録

### ISSUE THREAD

**Issue by lifu0** [NIFCloud-mbaas/UserCommunity#977]
●症状
下記サイトのデモプロジェクトをダウンロードして、実行すると、画面下のエラーが表示され、端末が登録できない。
エラー：「E403003　Operation that are prohibited.」
https://github.com/NIFCloud-mbaas/android_data_demo

クラス名がサンプルの「TestClass」だと正常に端末登録されるが、「installation」に変更するとエラーになる。

mBaas側の設定は手順通りに設定しています。
Androoid Studio 3.2.1
検証機種バージョン Android 6.0.1

●変更箇所
変更した箇所は、以下の2つです。
1.キーを変更
NCMB.initialize(this, "○○○○○", "○○○○○");

2.クラス名を「installation」に変更
NCMBObject obj = new NCMBObject("installation");

原因や解決方法がありましたらご教示ください。
よろしくお願いいたします。

![error](https://user-images.githubusercontent.com/46180475/50467772-0efc7700-09e8-11e9-91f4-576d8bc36f64.png)

**Comment by goofmint** [comment]
installationやuserは予約されているクラスなのでNCMBObjectからは触れません。 `NCMBInstallation` を使ってください。

https://mbaas.nifcloud.com/assets/sdk_doc/android/javadoc/index.html

**Comment by lifu0** [comment]
ご教示ありがとうございます。
getCurrentInstallation をふまえた形式に修正しましたが、今度はregistrationIdのエラーが表示されます。NCMBのSDKはv3なので、getRegistrationIdInBackground は使用できません。
修正方法をお教えいただけると幸いです。
       

　　final NCMBInstallation installation = NCMBInstallation.getCurrentInstallation();
        try {
            NCMBObject obj = new NCMBObject("installation");
            installation.put("message", "Hello, NCMB!");
            installation.saveInBackground(new DoneCallback() {
                @Override
                public void done(NCMBException e) {
                    if (e != null) {
                        //保存失敗
                        new AlertDialog.Builder(MainActivity.this)
                                .setTitle("Notification from NIFCLOUD")
                                .setMessage("Error:" + e.getMessage())
                                .setPositiveButton("OK", null)
                                .show();
                    } else {
                        //保存成功
                        new AlertDialog.Builder(MainActivity.this)
                                .setTitle("Notification from NIFCLOUD")
                                .setMessage("Save successfull! with ID:" + installation.getObjectId())
                                .setPositiveButton("OK", null)
                                .show();
                    }
                }
            });
        } catch (NCMBException e) {
            e.printStackTrace();
        }
![clipboard01](https://user-images.githubusercontent.com/46180475/50506015-02485380-0aba-11e9-9932-5a25aa0f7c00.png)

**Comment by goofmint** [comment]
エラーを見る限り、registrationIdが入っていないということではないでしょうか？

**Comment by lifu0** [comment]
アプリでregistrationIdをどうすれば入れる事ができるかが分からない状況です。

**Comment by goofmint** [comment]
手動でのInstrallation作成は通常やらない操作になりますので、APIドキュメントを参考にしてもらうのが良いかなと。

https://mbaas.nifcloud.com/assets/sdk_doc/android/javadoc/index.html

**Comment by lifu0** [comment]
Instrallationクラスは初めから作成されております。
上記のコードの中で不足箇所や、コーディングミスはありますでしょうか。

**Comment by goofmint** [comment]
何をしたいのかが分からないのですが、もしプッシュ通知を実装したいのであれば以下を参考にしてください。

https://mbaas.nifcloud.com/doc/current/push/basic_usage_android.html

自分でInstallationをいじる必要はなく、SDK側で行ってくれます。

**Comment by lifu0** [comment]
したいことは、データストアに端末を登録して、値を入れたいだけです。
様々サンプルを調べ、上記のコードになりましたが、 installation.saveInBackground でregistrationId がないとのエラーですので、何が間違えているか分からない状況になっています。

**Comment by goofmint** [comment]
データストアに端末を登録、というのがよく分からないのですが…。プッシュ通知を実装したいのでしょうか？

**Comment by lifu0** [comment]
分かりにくく申し訳ありません。
最終的にはプッシュ通知を実装する予定です。
installation にデータ登録がしたいです。そのことを端末登録といっていました。

**Comment by goofmint** [comment]
であれば、こちらを参考にして下さい。データストアを操作する必要はありません。

https://mbaas.nifcloud.com/doc/current/push/basic_usage_android.html
