### ISSUE TITLE
monaca、 mobilebackendでカラオケアプリは作れますか？

### ISSUE THREAD

**Issue by kasaishouhei** [NIFCloud-mbaas/UserCommunity#981]
monaca、 mobilebackendで自作の音源にのせたカラオケアプリを制作しようと考えていますが、音楽の再生やアップロード等の処理は分かりますが、技術的に音源を流しながら、音源と音声を同時に録音できるか分かりません。

**Comment by goofmint** [comment]
そこはmBaaSは関係ないのかなと。すでにiOSまたはAndroidアプリがあるならば、技術的にはできるのではないでしょうか。
