### ISSUE TITLE
会員一覧取得について

### ISSUE THREAD

**Issue by erohermit** [NIFCloud-mbaas/UserCommunity#997]
登録されている会員データを取得すると全てのデータが取得できません。
特に条件で絞っていないので、全件取得できるはずなのですが。

使用しているAPI
https://mbaas.api.nifcloud.com/2013-09-01/users?limit=1000&skip=0

会員数は400件ほどです。

データが取得できない条件ってありますでしょうか？

**Comment by goofmint** [comment]
ACLが引っかかっていないでしょうか？未ログインユーザに読み込み権限がないなど。

**Comment by erohermit** [comment]
その通りでした・・・。
初歩的なミスでお手数おかけしました
ありがとうございました！
